### PR TITLE
HDDS-3514. Fix memory leak of RaftServerImpl

### PR DESCRIPTION
**Pull request by runzhiwang**
## What changes were proposed in this pull request?
**This PR depends on [RATIS-845](https://github.com/apache/incubator-ratis/pull/76), we should wait RATIS-845 to merge.**

As the image shows, there are 1885 instances of  RaftServerImpl, most of them are Closed, and should be GC, but actually not. You can find from the image 
 1513 RaftServerImpl were held by ManagermentFactory->jxmMBeanServer->HashMap, 372 RaftServerImpl were held by Datanode ReportManager Thread -> prometheus -> HashMap. So 1513 RaftServerImpl leak in ratis, and 372 leak in ozone. If RaftServerImpl can not GC, there are a lot of related resource can not be GC, such as the [DirectByteBuffer](https://github.com/apache/incubator-ratis/blob/master/ratis-server/src/main/java/org/apache/ratis/server/raftlog/segmented/SegmentedRaftLogWorker.java#L150)  in SegmentRaftLogWorker, which result 1GB memory leak out of heap.

The reason RaftServerImpl held by ManagermentFactory->jxmMBeanServer->HashMap is ratis start [JmxReporter](https://github.com/apache/incubator-ratis/blob/master/ratis-metrics/src/main/java/org/apache/ratis/metrics/MetricsReporting.java#L47), but does not stop it.

The reason RaftServerImpl held by Datanode ReportManager Thread -> prometheus -> HashMap is ozone call the ratis function to  [register](https://github.com/apache/hadoop-ozone/blob/master/hadoop-hdds/container-service/src/main/java/org/apache/hadoop/ozone/HddsDatanodeService.java#L189) metric in prometheus, but does not unregister it.

**1. 1885 instances of RaftServerImpl**
image

**2. 1513 RaftServerImpl were held by ManagermentFactory->jxmMBeanServer->HashMap, 372 RaftServerImpl were held by Datanode ReportManager Thread -> prometheus -> HashMap**
image

**3. 1513 RaftServerImpl were held by ManagermentFactory->jxmMBeanServer->HashMap**
image

**4. 372 RaftServerImpl were held by Datanode ReportManager Thread -> prometheus -> HashMap**
image

5. 2038 DirectByteBuffer, and 1885 held by RaftServerImpl
image

6. 1033 DirectByteBuffer were held by ManagermentFactory, 802 DirectByteBuffer were held by Datanode ReportManager Thread, total 1885.
image

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3514

## How was this patch tested?

ungister prometheus and stopJmxReporter when removed in ratis.

### CODE REVIEW

**Comment by avijayanhwx** [comment]
I am working with @runzhiwang on reviewing the ratis changes in RATIS-845. Once that is done, I will review this as well.

**Comment by runzhiwang** [comment]
@avijayanhwx Could you help review it ? Thank you very much.

**Comment by adoroszlai** [comment]
/pending needs new Ratis snapshot (`b3cfec0e` or later) in Ozone

**Comment by arp7** [comment]
@bshashikant can you rebase the patch?

**Comment by runzhiwang** [comment]
duplicated with https://issues.apache.org/jira/browse/HDDS-3564. No need to merge.

**Pull request closed without merging**
