### PR TITLE
HDDS-2339. Add OzoneManager to MiniOzoneChaosCluster

### PR DESCRIPTION
**Pull request by hanishakoneru**
## What changes were proposed in this pull request?

This jira proposes to add OzoneManager to MiniOzoneChaosCluster with OzoneHA implementation done. This will help in discovering bugs in Ozone Manager HA

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-2339

## How was this patch tested?

Tested by running chaos cluster locally.

### CODE REVIEW

**Comment by hanishakoneru** [comment]
Thanks for the review @mukul1987.

> Also with the current patch, it will be difficult to run a version of chaos with both the failure modes. Can we please organize the OM and DN failure code inside the MiniOzoneChaosCluster class itself.
I do see advantages of starting either the OM and DN version separately, but I feel a combined version is also important.

Agree. I was planning on working on that in a separate Jira.

**Comment by hanishakoneru** [comment]
> Can we also add an optional paramenter to the shell script to run the om failure version too ?

@mukul1987, can you please tell which shell script? TestMiniChaosOzoneCluster has the changes to run the test. Is there somewhere else we need this change?

**Comment by nandakumar131** [comment]
@hanishakoneru 
FYI: we have merge conflicts.

**Comment by hanishakoneru** [comment]
@nandakumar131 I had fixed the merge conflict. Can you please check again.
The acceptance test run did not complete. I will re-trigger the checks.

**Comment by hanishakoneru** [comment]
@mukul1987, @nandakumar131 can you please take a look.

**Comment by arp7** [comment]
Folks - any further comments on this? If not can we get this in?

**Comment by nandakumar131** [comment]
I will take a look at it tomorrow.

**Comment by nandakumar131** [comment]
Thanks @hanishakoneru  for taking care of this. I don't have any major comments. We can merge it once @mukul1987 is ok with it.

**Pull request merged**
