### PR TITLE
HDDS-3564. Update Ozone to latest Ratis Snapshot (0.6.0-3596a58-SNAPSHOT).

### PR DESCRIPTION
**Pull request by mukul1987**
## What changes were proposed in this pull request?
Update Ozone to latest Ratis Snapshot(0.6.0-1720b1f-SNAPSHOT).

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3564

## How was this patch tested?
Build was successful.

### CODE REVIEW

**Comment by elek** [comment]
Thanks to create this PR @mukul1987.

How does it related to #890? Does it replace the earlier one?

My overall proposal is to do at least 3-5 commit/CI build before merging new Ratis version and analyze all the failures before merging. Earlier we introduced intermittent test failures with Ratis upgrade and we should be sure that the new version is stable enough..

**Comment by mukul1987** [comment]
@elek, this replaces the earlier commit at  #890, as this is at a later ratis commit. Sure, lets run 4-5 iterations.

**Comment by hanishakoneru** [comment]
@mukul1987 we need another commit - RATIS-874 to fix snapshots in OM. 
Can we include that also in this PR. If this PR is close to merge, I will open another Jira. Please let me know. Thanks.

**Comment by mukul1987** [comment]
@hanishakoneru , I can spin off another snapshot release

**Comment by hanishakoneru** [comment]
@mukul1987 I deployed **0.6.0-3596a58-SNAPSHOT** to apache repository.

**Comment by mukul1987** [comment]
@hanishakoneru I have updated the patch with the new snapshot.

**Comment by hanishakoneru** [comment]
Thanks @mukul1987

**Comment by mukul1987** [comment]
The frequent test failures here are fixed via HDDS-3601 and HDDS-3602

**Comment by elek** [comment]
> The frequent test failures here are fixed via HDDS-3601 and HDDS-3602

Both are merged. I suppose we will have mostly green builds after a rebase.

**Comment by elek** [comment]
#08a3495 is failed with timeout, and it seems to be Ratis related:

```
2020-05-20 09:55:02,620 [java.util.concurrent.ThreadPoolExecutor$Worker@687b99c3[State = -1, empty queue]] WARN  server.GrpcLogAppender (GrpcLogAppender.java:timeoutAppendRequest(213)) - 1cbabd32-0c3f-4f38-ae01-b2b3d9193852@group-0A8E2870BF3C->4f19e3ae-b4d5-46dd-b016-d762b73ce108-GrpcLogAppender:  appendEntries Timeout, request=AppendEntriesRequest:cid=117,entriesCount=1,lastEntry=(t:1, i:100)
2020-05-20 09:55:02,622 [java.util.concurrent.ThreadPoolExecutor$Worker@687b99c3[State = -1, empty queue]] WARN  server.GrpcLogAppender (GrpcLogAppender.java:timeoutAppendRequest(213)) - 1cbabd32-0c3f-4f38-ae01-b2b3d9193852@group-0A8E2870BF3C->4f19e3ae-b4d5-46dd-b016-d762b73ce108-GrpcLogAppender:  appendEntries Timeout, request=AppendEntriesRequest:cid=118,entriesCount=1,lastEntry=(t:1, i:101)
```

This is something which we have seen earlier, but it supposed to be fixed with RATIS-840. 

Do you have any idea what is the root cause?

What do you suggest with this version bump?

**Comment by elek** [comment]
> What do you suggest with this version bump?

ping @lokeshj1703, @mukul1987

**Comment by adoroszlai** [comment]
> What do you suggest with this version bump?

I propose:

* creating yet another Ratis snapshot from current `master` and updating to Ozone that one
* investigating all CI failures after that update

Reasons:

* Current situation with intermittent problems is already pretty bad.  It may get a bit better or worse with this upgrade, but not significantly.
* I don't think we have the resources to investigate both old and new failures.
* Previous Ratis upgrades were usually done without repeated tests (even as part of other, functional changes).

Further proposals:

0. Archive failures of `pr-check`, too (currently only `post-commit` on `master` is archived), to get info on significantly more CI runs, ie. more data points.
1. Create Ratis snapshot release more frequently (automate it?).
2. Test Ozone with each "significant" snapshot (eg. one that is not a test-only or build infrastructure change) on a dedicated branch.  Also archive these runs.

**Comment by elek** [comment]
Thanks the proposal @adoroszlai. I have seen acceptance test timeouts in the previous builds (which is not on the master). I think it should be checked before the merge (if visible with the latest snapshot). It's the same effort to check here or the master, but on master makes the merge of PRs harder. 

> Further proposals:

And thank you for the proposals:

> Archive failures of pr-check, too (currently only post-commit on master is archived), to get info on significantly more CI runs, ie. more data points.

We can do it. It requires more space and it will include a lot of noise (failures which are real failures). We need some smart filtering (eg. check only the failures which are passed later with a different build but no difference between the two commits).

> Create Ratis snapshot release more frequently (automate it?).

We can check the purge policy on snapshot.apache.org. If snapshots are kept until the next release we can do a daily snapshot build and use `mvn versions:lock-snapshots` + `versions:unlock-snapshots` commands (it replaces a SNAPSHOT version with an exact timestamped version)

> Test Ozone with each "significant" snapshot (eg. one that is not a test-only or build infrastructure change) on a dedicated branch. Also archive these runs.

+1. We can create a daily build with full Ozone + latest Ratis. Would help a lot IMHO.

**Comment by elek** [comment]
This patch seems to have problems which are not on the master. Would be great to investigate them: 

One example:

{code}
java.io.IOException: java.lang.IllegalStateException: org.apache.ratis.util.Preconditions$$Lambda$155/1521443176@2c865c75
{code}

**Comment by mukul1987** [comment]
Thanks @elek, Yes, I have updated the PR, this once again tries to update the Ratis version to get to a more stable version.

**Comment by elek** [comment]
#fd26e7fbfcfcc2a362f9268c3078cb73c41b97a2 failed with an error which is very similar to this failure on the master: 

https://github.com/elek/ozone-build-results/tree/master/2020/06/05/982/it-freon/hadoop-ozone/integration-test

**Comment by elek** [comment]
#0e98352 is failed with it-client failure: 

`TestBlockOutputStreamWithFailuresFlushDelay`

This test has never been failed on mater earlier:

```
test2DatanodesFailure(org.apache.hadoop.ozone.client.rpc.TestBlockOutputStreamWithFailuresFlushDelay)  Time elapsed: 54.166 s  <<< FAILURE!
java.lang.AssertionError: expected:<500> but was:<400>
        at org.junit.Assert.fail(Assert.java:88)
```

**Comment by mukul1987** [comment]
@elek , this is a new test added on 04/June/2020, I do not think this test has been there for long enough to conclude that this test always passes.

**Comment by elek** [comment]
#ee77d6c is failed because `TestOzoneManagerHAWithData` with the following exception:

```
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ozone.om.exceptions.OMLeaderNotReadyException): omNode-2@group-523986131536 is in LEADER state but not ready yet.
```

The same test is failed 4 times on the master recently:

```
./2020/06/05/985/it-hdds-om/hadoop-ozone/integration-test/org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData-output.txt
./2020/06/05/985/it-hdds-om/hadoop-ozone/integration-test/TEST-org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData.xml
./2020/06/05/985/it-hdds-om/hadoop-ozone/integration-test/org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData.txt
./2020/06/02/947/it-hdds-om/hadoop-ozone/integration-test/org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData-output.txt
./2020/06/02/948/it-hdds-om/hadoop-ozone/integration-test/org.apache.hadoop.ozone.om.TestOzoneManagerHAWithData-output.txt
```

But I didn't see the same exception in the saved logs.

**Comment by mukul1987** [comment]
Thanks for taking a look at this issue @elek. I have seen this issue earlier as well. 
`org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ozone.om.exceptions.OMLeaderNotReadyException): omNode-2@group-523986131536 is in LEADER state but not ready yet.
`

**Pull request merged**
