### PR TITLE
HDDS-2267. Container metadata scanner interval mismatch

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Fix time unit mismatch in container metadata scanner.  Elapsed time is measured in nanoseconds, needs to be converted to milliseconds.

https://issues.apache.org/jira/browse/HDDS-2267

## How was this patch tested?

Tested on `ozone` docker-compose cluster.

```
datanode_1  | 2019-10-09 06:18:00 INFO  ContainerMetadataScanner:60 - Background ContainerMetadataScanner starting up
datanode_1  | 2019-10-09 06:18:00 INFO  ContainerMetadataScanner:88 - Completed an iteration of container metadata scrubber in 0 minutes. Number of  iterations (since the data-node restart) : 1, Number of containers scanned in this iteration : 0, Number of unhealthy containers found in this iteration : 0
datanode_1  | 2019-10-09 06:19:00 INFO  ContainerMetadataScanner:88 - Completed an iteration of container metadata scrubber in 0 minutes. Number of  iterations (since the data-node restart) : 2, Number of containers scanned in this iteration : 2, Number of unhealthy containers found in this iteration : 0
...
datanode_1  | STARTUP_MSG: Starting HddsDatanodeService
datanode_1  | 2019-10-09 06:23:52 INFO  ContainerMetadataScanner:60 - Background ContainerMetadataScanner starting up
datanode_1  | 2019-10-09 06:23:52 INFO  ContainerMetadataScanner:88 - Completed an iteration of container metadata scrubber in 0 minutes. Number of  iterations (since the data-node restart) : 1, Number of containers scanned in this iteration : 2, Number of unhealthy containers found in this iteration : 0
datanode_1  | 2019-10-09 06:24:52 INFO  ContainerMetadataScanner:88 - Completed an iteration of container metadata scrubber in 0 minutes. Number of  iterations (since the data-node restart) : 2, Number of containers scanned in this iteration : 2, Number of unhealthy containers found in this iteration : 0
```

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
Thanks @adoroszlai  for fixing this. The change LGTM.

**Comment by elek** [comment]
My previous comments are not addressed but it was an optional suggestion. I commit it right now as it's better than the current code.

From the old PR:




Thanks to fix it @adoroszlai. Nice catch.

As the millisecond resolution is enough I think it can be more safer to use type-safe java API:

Sg like:

```
Instant start = Instant.now();

...

nextCheck = start.plus(metadataScanInterval, ChronoUnit.SECONDS)
remainingMs = Instant.now().until(nextCheck, ChronoUnit.MILLIS)
Time.sleep(remainingMs)
```

But I am also fine with the current patch as it's definitely better than the earlier code ;-)

**Comment by adoroszlai** [comment]
Thanks @xiaoyuyao for the review.  Thanks @elek for reviewing and committing it.  I like your idea about using type-safe time objects and applied it to #7.  But here I wanted to minimize the change.

**Comment by elek** [comment]
>  But here I wanted to minimize the change.

Fair enough, and it seems to be a good newbie jira, I will create one...

**Pull request closed without merging**
