### PR TITLE
HDDS-2272. Avoid buffer copying in GrpcReplicationClient

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Eliminate `BufferedOutputStream`, write `ByteString` directly to `FileStream` to avoid a buffer copy.
Also, use `ByteString.writeTo(OutputStream)`, although it still seems to copy the byte array internally.

https://issues.apache.org/jira/browse/HDDS-2272

## How was this patch tested?

Tested closed container replication manually with a 300MB container.  Verified that container is correctly replicated to other datanode.

### CODE REVIEW

**Comment by adoroszlai** [comment]
@szetszwo please review

**Comment by szetszwo** [comment]
+1 the change looks good.

**Comment by arp7** [comment]
@bharatviswa504 can you take a look at the `TestOzoneManagerDoubleBufferWithDummyResponse` failure? Does the test need to be fixed?

**Comment by elek** [comment]
Committing it to the master. Thanks @adoroszlai the patch and @szetszwo the review.

**Comment by adoroszlai** [comment]
Thanks @szetszwo for reviewing and @elek for committing it.  Also thanks @arp7 and @bharatviswa504 for checking the test issue.

**Pull request closed without merging**
