### PR TITLE
HDDS-2310. Add support to add ozone ranger plugin to Ozone Manager cl…

### PR DESCRIPTION
**Pull request by vivekratnavel**
…asspath.

## What changes were proposed in this pull request?

This PR adds a new hadoop shell profile for ozone manager to be able to extend Ozone Manager's classpath. It is implemented in a generic way and is not exclusive to ranger plugin. Any path can be added to Ozone Manager classpath by setting the env variable `OZONE_MANAGER_CLASSPATH`

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-2310

## How was this patch tested?

Tested by running ozone manager locally with the above mentioned env set to some path.
```
 export OZONE_MANAGER_CLASSPATH=/tmp/*
./hadoop-ozone/dist/target/ozone-0.5.0-SNAPSHOT/bin/ozone --debug om
```

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@elek @avijayanhwx @bharatviswa504 Please review.

**Comment by avijayanhwx** [comment]
LGTM +1

**Comment by anuengineer** [comment]
There are few test failures, @vivekratnavel can you please take a look ? Thanks in advance,

**Comment by anuengineer** [comment]
@vivekratnavel  I don't think these failures are yours but any change to CLASS_PATH needs triple verification. Hence I am asking you to check and make sure on your system. Thanks. I have seen some these tests fail past few days.

**Comment by bharatviswa504** [comment]
We have found a way to do this, so we don't need this PR.

**Comment by vivekratnavel** [comment]
@avijayanhwx @anuengineer @bharatviswa504 Thanks for the review!

I have updated the patch with a minor change as @bharatviswa504 mentioned after discussion with @elek. Now, setting `/path/to/dir/*` as `OZONE_MANAGER_CLASSPATH` env variable, adds all the files inside the given dir to Ozone Manager's classpath.

This behavior was tested in a live cluster by setting `OZONE_MANAGER_CLASSPATH` and starting up Ozone Manager and verifying its classpath during startup.

**Comment by vivekratnavel** [comment]
@anuengineer The integration test failures are not related.

**Comment by bharatviswa504** [comment]
Thank You @vivekratnavel for the contribution and all  for the review.

**Pull request merged**
