### PR TITLE
[WIP] HDDS-3599. Implement ofs://: Add contract test for HA

### PR DESCRIPTION
**Pull request by smengcl**
## What changes were proposed in this pull request?

OFS: Add contract test for HA scenario.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3599

## How was this patch tested?

Tested by itself.

### CODE REVIEW

**Comment by timmylicheng** [comment]
Hey Siyao, not sure why, but it looks like https://issues.apache.org/jira/browse/HDDS-3559 is linked to his JIRA. I think you mean to link to HDDS-3599. Could you do manual correction for it?

**Comment by smengcl** [comment]
> Hey Siyao, not sure why, but it looks like https://issues.apache.org/jira/browse/HDDS-3559 is linked to his JIRA. I think you mean to link to [HDDS-3599](https://issues.apache.org/jira/browse/HDDS-3599). Could you do manual correction for it?

Ah sorry about the typo. Thanks @elek for correcting it.

**Comment by smengcl** [comment]
Just a note. There is an integration test timeout issue when running on my Mac. Every time a second HA cluster is run all the tests in that test suite times out for me. But in pr-check in Github Actions it runs [just fine](https://github.com/apache/hadoop-ozone/pull/928/checks?check_run_id=680451326) (it fails for other normal reasons).

**Comment by elek** [comment]
Is it still a WIP patch or ready to review?

**Comment by smengcl** [comment]
> Is it still a WIP patch or ready to review?

Not yet. I still got some issues that I need to address (plus the other mini HA cluster launch/destroy stuck issue that doesn't seem to be reproducible on upstream)

**Pull request closed without merging**
