### PR TITLE
HDDS-3398. Update grpc/netty dependencies

### PR DESCRIPTION
**Pull request by mukul1987**
## What changes were proposed in this pull request?

Upgate grpc/netty dependencies in ozone

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3398

## How was this patch tested?
Ran MiniOzoneChaosCluster test.

### CODE REVIEW

**Comment by elek** [comment]
Thanks to create this patch @mukul1987 

Would be great to test CSI server. I found that the CSI server is broken since the last netty upgrade in ratis-third-party (0.2.0->0.3.0)

**Comment by elek** [comment]
@arp7 was the CSI server tested?

**Comment by elek** [comment]
I tested it and it didn't work. Would you be so kind to use 4.1.38 instead of 4.1.48? I couldn't see any CVE with 4.1.38 and it doesn't break CSI server.

**Comment by arp7** [comment]
Sorry looks like I jumped the gun on the commit.

**Comment by mukul1987** [comment]
@elek, How can the CSI server can be tested, is there an acceptance test available ?

**Comment by elek** [comment]
> @elek, How can the CSI server can be tested, is there an acceptance test available ?

The easiest way is just start the "ozone csi" command. If it can be started (and a socket is created) than it should be fine. 

You need to `ozone-site.xml` configuration:  `ozone.csi.owner=hadoop` and `ozone.csi.socket=/tmp/csi.socket`

I created an acceptance test, will create a PR soon. Are you happy with using 4.1.38 instead of 4.1.48?

**Pull request merged**
