### PR TITLE
HDDS-3601. Refactor TestOzoneManagerHA.java into multiple tests to avoid frequent timeout issues.

### PR DESCRIPTION
**Pull request by mukul1987**
## What changes were proposed in this pull request?
Refactor TestOzoneManagerHA into multiple smaller tests

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3601

## How was this patch tested?
All the 3 new tests pass.

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
+1 from me too. Thanks for fixing this.

**Comment by xiaoyuyao** [comment]
Agree this will help the timeout issue of individual tests. But we have a 900s surefire timeout per test module. If they are still under the same module, we still might hit the surefire timeout as observed in latest #923 run.

**Comment by bharatviswa504** [comment]
LGTM.

One question I have is we have a time out rule of 5 minutes, this is applicable for each test right? Splitting it to multiple tests how will it solve the issue?

**Comment by elek** [comment]
Good point @bharatviswa504

**Comment by adoroszlai** [comment]
> One question I have is we have a time out rule of 5 minutes, this is applicable for each test right?

Where is this 5-min timeout defined?

**Comment by bharatviswa504** [comment]
> > One question I have is we have a time out rule of 5 minutes, this is applicable for each test right?
> 
> Where is this 5-min timeout defined?

I mean here for the tests of HA, we have a rule 
  @Rule
  public Timeout timeout = new Timeout(300_000);

**Comment by bharatviswa504** [comment]
> https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html

Thank You @elek for the clear explanation. Now, it makes sense.

**Comment by elek** [comment]
Thanks @mukul1987 the patch. (and @bharatviswa504, @adoroszlai, @xiaoyuyao, @hanishakoneru  the review and the discussion). 

I am merging it to the master...

**Pull request closed without merging**
