### PR TITLE
HDDS-3989. Display revision and build date of DN in recon UI

### PR DESCRIPTION
**Pull request by runitao**
## What changes were proposed in this pull request?

People can get more detailed version info about DN in recon UI.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3989

## How was this patch tested?

Test in docker-compose environment
image

Test in `pnpm run dev` and code is linted with `yarn run lint:fix`
image

### CODE REVIEW

**Comment by vivekratnavel** [comment]
//retest

**Comment by runitao** [comment]
```
Log:     /mnt/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT/compose/upgrade/result/log.html
Report:  /mnt/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT/compose/upgrade/result/report.html
cp: cannot stat '/mnt/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT/compose/upgrade/result/*.out*': No such file or directory
Log:     /mnt/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT/compose/result/log.html
Report:  /mnt/ozone/hadoop-ozone/dist/target/ozone-0.6.0-SNAPSHOT/compose/result/report.html
Exception in thread "main" 
##[error]Process completed with exit code 1.
```

trigger CI again

**Comment by runitao** [comment]
@vivekratnavel Since the CI passed, can we merge this PR. Thanks.

**Comment by vivekratnavel** [comment]
@runitao Thanks for working on this!

**Comment by elek** [comment]
Hi, thanks for the contributions @runitao, it's very useful for the UI.

 It looked good to me, but when I analyzed the network traffic found that the two new fields are added two all the requests as the DatanodeInfo protocol is a shared type.

For example when I do `createKey` or block allocations the new fields are added. Which means that the performance is worse in case of many small keys. I think it can be better to further improve it and add the fields only to the SCM registration type.

**Comment by vivekratnavel** [comment]
@elek Good catch! I have created a jira to track this - https://issues.apache.org/jira/browse/HDDS-4039

**Comment by runitao** [comment]
Thanks for your suggestion @elek. And thank you for assigning HDDS-4039 for me, @vivekratnavel, I will fix that.

**Pull request merged**
