### PR TITLE
HDDS-3279. Rebase OFS branch

### PR DESCRIPTION
**Pull request by smengcl**
## What changes were proposed in this pull request?

Merge commits on master branch to OFS dev branch: `git merge master`

Also need to manually apply a couple of changes in master branch to OFS classes:
- HDDS-3049
- HDDS-2914 (HDDS-2188)
- HDDS-3065

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3279

## How was this patch tested?

- [x] Compile passed with `mvn clean install -Pdist -DskipTests -e -Dmaven.javadoc.skip=true -DskipShade`
- [x] Ran `TestRootedOzoneFileSystem` and passed locally.
- [x] Test OFS manually in shell. The following commands work as expected.
```bash
$ ozone fs -ls ofs://om/
$ ozone fs -mkdir ofs://om/volume1/
2020-03-25 16:33:41,747 [main] INFO rpc.RpcClient: Creating Volume: volume1, with hadoop as owner.
$ ozone fs -mkdir ofs://om/volume1/bucket1/
2020-03-25 16:33:50,120 [main] INFO rpc.RpcClient: Creating Bucket: volume1/bucket1, with Versioning false and Storage Type set to DISK and Encryption set to false
$ ozone fs -mkdir ofs://om/volume1/bucket1/dir1/
$ ozone fs -mkdir ofs://om/volume1/bucket1/dir1/subdir1/
$ ozone fs -put README.md ofs://om/volume1/bucket1/dir1/subdir1/
2020-03-25 16:34:17,686 [main] INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
2020-03-25 16:34:17,825 [main] INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
2020-03-25 16:34:17,825 [main] INFO impl.MetricsSystemImpl: XceiverClientMetrics metrics system started
$ ozone fs -ls -R ofs://om/
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1/bucket1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1/bucket1/dir1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:34 ofs://om/volume1/bucket1/dir1/subdir1
-rw-rw-rw-   1 hadoop hadoop       3820 2020-03-25 16:34 ofs://om/volume1/bucket1/dir1/subdir1/README.md
```
```bash
$ ozone fs -mkdir -p ofs://om/volume2/bucket2/
2020-03-25 16:35:33,089 [main] INFO rpc.RpcClient: Creating Volume: volume2, with hadoop as owner.
2020-03-25 16:35:33,122 [main] INFO rpc.RpcClient: Creating Bucket: volume2/bucket2, with Versioning false and Storage Type set to DISK and Encryption set to false
$ ozone fs -mkdir -p ofs://om/volume3/bucket3/dir3/subdir3/
2020-03-25 16:35:45,961 [main] INFO rpc.RpcClient: Creating Volume: volume3, with hadoop as owner.
2020-03-25 16:35:45,993 [main] INFO rpc.RpcClient: Creating Bucket: volume3/bucket3, with Versioning false and Storage Type set to DISK and Encryption set to false
```
```bash
$ ozone sh volume create tmp
$ ozone sh volume setacl tmp -al world::a
ACL(s) set successfully.
$ ozone fs -ls ofs://om/tmp/
ls: `ofs://om/tmp/': No such file or directory
$ ozone fs -mkdir ofs://om/tmp/
2020-03-25 16:38:30,567 [main] INFO rpc.RpcClient: Creating Bucket: tmp/0238775c7bd96e2eab98038afe0c4279, with Versioning false and Storage Type set to DISK and Encryption set to false
$ ozone fs -ls ofs://om/tmp/
$ ozone fs -put NOTICE.txt ofs://om/tmp/
2020-03-25 16:39:10,258 [main] INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
2020-03-25 16:39:10,402 [main] INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
2020-03-25 16:39:10,402 [main] INFO impl.MetricsSystemImpl: XceiverClientMetrics metrics system started
$ ozone fs -put *.md ofs://om/tmp/
2020-03-25 16:39:22,378 [main] INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
2020-03-25 16:39:22,526 [main] INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
2020-03-25 16:39:22,526 [main] INFO impl.MetricsSystemImpl: XceiverClientMetrics metrics system started
$ ozone fs -ls ofs://om/tmp/
Found 2 items
-rw-rw-rw-   1 hadoop hadoop      17540 2020-03-25 16:39 ofs://om/tmp/NOTICE.txt
-rw-rw-rw-   1 hadoop hadoop       3820 2020-03-25 16:39 ofs://om/tmp/README.md
```
```bash
$ ozone fs -ls ofs://om/
Found 4 items
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:37 ofs://om/tmp
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume2
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume3
$ ozone fs -ls -R ofs://om/
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1/bucket1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:33 ofs://om/volume1/bucket1/dir1
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:34 ofs://om/volume1/bucket1/dir1/subdir1
-rw-rw-rw-   1 hadoop hadoop       3820 2020-03-25 16:34 ofs://om/volume1/bucket1/dir1/subdir1/README.md
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume2
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume2/bucket2
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume3
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume3/bucket3
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume3/bucket3/dir3
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:35 ofs://om/volume3/bucket3/dir3/subdir3
drwxrwxrwx   - hadoop hadoop          0 2020-03-25 16:37 ofs://om/tmp
-rw-rw-rw-   1 hadoop hadoop      17540 2020-03-25 16:39 ofs://om/tmp/NOTICE.txt
-rw-rw-rw-   1 hadoop hadoop       3820 2020-03-25 16:39 ofs://om/tmp/README.md
```

## NOTE

- DO NOT MERGE this PR from Github. Because merging from Github will squash the merged commits from master branch. This PR is for review and discussion purpose only. Should've submitted this one as a draft PR as I think of that.
- Only the last 3 commits are actual changes we are looking into in this PR:
  - https://github.com/apache/hadoop-ozone/pull/721/commits/25480ce9192d6cab91d0e2037821ac80b7ebe2bd
  - https://github.com/apache/hadoop-ozone/pull/721/commits/5fb9d7d8f21930d6636325e00240df6d1dddfe95
  - https://github.com/apache/hadoop-ozone/pull/721/commits/d8775d1853355c3e5ce649a94c9af6507bd18831

### CODE REVIEW

**Comment by jojochuang** [comment]
You actually don't need to submit a PR. Simply git pull --rebase, and then git push -f to force push the branch. But good to see additional check after the rebase.

**Comment by smengcl** [comment]
> You actually don't need to submit a PR. Simply git pull --rebase, and then git push -f to force push the branch. But good to see additional check after the rebase.

Yep the way you mentioned (pull rebase + force push) is my preferred way to do a rebase. Thanks for the tip nevertheless.

Since Xiaoyu and I were already using `git merge` previously I think I'd keep it consistent for this dev branch.

**Comment by smengcl** [comment]
Test failure assessment:
- acceptance failure is from smoketest `ozonesecure-mr-mapreduce`. I recall witnessing the same failure before but not doing anything to fix it - possibly a flaky one.
- it-filesystem failure simply results from some tests skipped because of the acceptance failure it seems. 
```
[INFO] Results:
[INFO] 
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Skipping Apache Hadoop Ozone Mini Ozone Chaos Tests
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Hadoop Ozone Integration Tests 0.5.0-SNAPSHOT:
[INFO] 
[INFO] Apache Hadoop Ozone Integration Tests .............. FAILURE [25:14 min]
```

Retriggering the tests.

**Comment by xiaoyuyao** [comment]
+1. Please go ahead push the change **outside github as Squash and merge is the only option with github.**

**Comment by smengcl** [comment]
Thanks @xiaoyuyao . I am going to do the following:
1. Close this PR;
2. Merge master commits to OFS dev branch manually;
3. Create a new PR with only the 3 commits I posted in this PR already;
4. Merge that new PR.

**Pull request closed without merging**
