### PR TITLE
HDDS-3813. Integrate with ratis 1.0.0 release binaries for ozone 0.6.0 release.

### PR DESCRIPTION
**Pull request by lokeshj1703**
## What changes were proposed in this pull request?

Update ratis version to 1.0.0

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3813

## How was this patch tested?

Existing UT

### CODE REVIEW

**Comment by adoroszlai** [comment]
Can we please avoid merging with failed checks?  Although there are some flaky tests, I don't think acceptance test timeout should be ignored, especially because the same failure happened in both [PR](https://github.com/apache/hadoop-ozone/runs/889340487) and [push](https://github.com/lokeshj1703/hadoop-ozone/runs/889331974) runs.

**Comment by adoroszlai** [comment]
Built fb2649e14 locally, got this in acceptance test:

```
datanode_3  | 2020-07-21 09:48:07,890 [main] ERROR ozone.HddsDatanodeService: Exception in HddsDatanodeService.
datanode_3  | java.lang.NoClassDefFoundError: org/apache/ratis/thirdparty/com/google/protobuf/ProtocolMessageEnum
datanode_3  | 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
datanode_3  | 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
datanode_3  | 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
datanode_3  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
datanode_3  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
datanode_3  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
datanode_3  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
datanode_3  | 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
datanode_3  | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
datanode_3  | 	at org.apache.hadoop.ozone.container.common.helpers.ContainerMetrics.<init>(ContainerMetrics.java:59)
datanode_3  | 	at org.apache.hadoop.ozone.container.common.helpers.ContainerMetrics.create(ContainerMetrics.java:94)
datanode_3  | 	at org.apache.hadoop.ozone.container.ozoneimpl.OzoneContainer.<init>(OzoneContainer.java:104)
datanode_3  | 	at org.apache.hadoop.ozone.container.common.statemachine.DatanodeStateMachine.<init>(DatanodeStateMachine.java:116)
datanode_3  | 	at org.apache.hadoop.ozone.HddsDatanodeService.start(HddsDatanodeService.java:245)
datanode_3  | 	at org.apache.hadoop.ozone.HddsDatanodeService.start(HddsDatanodeService.java:191)
datanode_3  | 	at org.apache.hadoop.ozone.HddsDatanodeService.call(HddsDatanodeService.java:166)
datanode_3  | 	at org.apache.hadoop.ozone.HddsDatanodeService.call(HddsDatanodeService.java:84)
datanode_3  | 	at picocli.CommandLine.execute(CommandLine.java:1173)
datanode_3  | 	at picocli.CommandLine.access$800(CommandLine.java:141)
datanode_3  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
datanode_3  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
datanode_3  | 	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
datanode_3  | 	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
datanode_3  | 	at picocli.CommandLine.parseWithHandler(CommandLine.java:1465)
datanode_3  | 	at org.apache.hadoop.hdds.cli.GenericCli.execute(GenericCli.java:75)
datanode_3  | 	at org.apache.hadoop.hdds.cli.GenericCli.run(GenericCli.java:66)
datanode_3  | 	at org.apache.hadoop.ozone.HddsDatanodeService.main(HddsDatanodeService.java:149)
datanode_3  | Caused by: java.lang.ClassNotFoundException: org.apache.ratis.thirdparty.com.google.protobuf.ProtocolMessageEnum
datanode_3  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
datanode_3  | 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
datanode_3  | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by adoroszlai** [comment]
I think this is caused by leaving `ratis-thirdparty-misc` at 0.4.0.  Submitted follow-up PR #1229.

**Comment by elek** [comment]
> Can we please avoid merging with failed checks? Although there are some flaky tests, I don't think acceptance test timeout should be ignored, especially because the same failure happened in both PR and push runs.

+1

I think it's time to explicit disable the merge button if something is failing. Will create an INFRA ticket.

**Pull request merged**
