### PR TITLE
HDDS-2621. Enable OM HA acceptance tests.

### PR DESCRIPTION
**Pull request by hanishakoneru**
## What changes were proposed in this pull request?

OM HA robot tests were disable in HDDS-2533 as they were failing intermittently. HDDS-2454 fixes some issues in the HA tests. Creating this Jira so as to run re-enable the HA acceptance tests.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-2621

## How was this patch tested?

CI acceptance test suit.

### CODE REVIEW

**Comment by elek** [comment]
OM ha test is failing in this patch:

```
OSError: [Errno 13] Permission denied: '/opt/hadoop/tmptWKCFH'
```

In github actions based runs the `/opt/hadoop` might not be writable. `/tmp` is a better choice for temporary data...

**Comment by adoroszlai** [comment]
@hanishakoneru I tried to fix this, found the following two changes necessary:

* use temp dir as @elek suggested: bf57d0e6f89b2434efb7e9dd59b5480ad1c80166
* fix SSH keys: 9df5d0838ad402b79bcbece2c4831d82a55904c6

The test still doesn't pass completely, [latest run](https://github.com/adoroszlai/hadoop-ozone/runs/357768776) failed with `copyFromLocal: Allocate any more blocks for write failed`.  If you have time, please feel free to pick these two changes and continue from there.

**Comment by hanishakoneru** [comment]
Thanks @adoroszlai and @elek. 
I have incorporated your suggestions. The tests are passing locally. I will let CI run once again to see whats happening.

**Comment by hanishakoneru** [comment]
Thanks @adoroszlai for verifying. 

I set to "pending" so that someone does not merge this change by mistake as there is 1 approval already :)

**Comment by xiaoyuyao** [comment]
> OM ha test is failing in this patch:
> 
> ```
> OSError: [Errno 13] Permission denied: '/opt/hadoop/tmptWKCFH'
> ```
> 
> In github actions based runs the `/opt/hadoop` might not be writable. `/tmp` is a better choice for temporary data...

I'm seeing something similar on some of the PR runs but not all. Like #520 I mentioned. Can you confirm @hanishakoneru  if this is the same issue.

2019-11-16T12:01:24.9714368Z Test Multiple Failovers | FAIL |
2019-11-16T12:01:24.9715403Z OSError: [Errno 13] Permission denied: '/opt/hadoop/tmpLn9PKJ'

**Comment by hanishakoneru** [comment]
@xiaoyuyao, this is the same issue but I am surprised how the OM-HA tests are running when they are disabled. Can you please point to another PR where you observed this. I don't see HA tests in #520 .

**Comment by hanishakoneru** [comment]
Thank you all for the reviews and suggestions. I will merge this shortly.

**Comment by elek** [comment]
Test is failed on the master after the merge: https://github.com/apache/hadoop-ozone/actions/runs/67591808

**Comment by adoroszlai** [comment]
> Test is failed on the master after the merge: https://github.com/apache/hadoop-ozone/actions/runs/67591808

And no OM logs are available: https://issues.apache.org/jira/browse/HDDS-3311

**Comment by elek** [comment]
Two more failures:

 * https://github.com/apache/hadoop-ozone/actions/runs/68224789
 * https://github.com/apache/hadoop-ozone/actions/runs/68191219

I hate to be the bad guy (again), and I am very sorry, but I have to revert/reopen it as it's failed 3 times from the last 6 master build.

**Comment by elek** [comment]
Ok. Instead of revert, I just excluded the tests from the pr / daily build. We can create an other pull request and start to test it (#ce6ad30a3)

**Comment by elek** [comment]
I will create a separated github action to make it easier to run only one acceptance test multiple times...

**Comment by elek** [comment]
If I didn't do any mistake, the om-ha tests (and only them) will be executed twice per hour here:

https://github.com/elek/hadoop-ozone/actions?query=workflow%3Aacceptance-single

https://github.com/elek/hadoop-ozone/commit/da01f32a21626a4c0851f5ca601c29a1b802a818

**Comment by hanishakoneru** [comment]
Thanks @elek for disabling this test. These OM HA failures are very elusive. I tested multiple times before merging and they didnt fail any of those times. 
Hoping that your github actions for running ha tests will tell us something. Thanks for setting that up.

**Comment by elek** [comment]
It seems to be flaky.  Got a lot of runs and 7 out of the last 25 are failed. (Yes, hard to detect this number, because you might have even 3 green builds without detecting them). 

Examples:

https://github.com/elek/hadoop-ozone/runs/554176250
https://github.com/elek/hadoop-ozone/actions/runs/68771264
https://github.com/elek/hadoop-ozone/actions/runs/68745626
https://github.com/elek/hadoop-ozone/actions/runs/68694305

**Pull request merged**
