### PR TITLE
HDDS-2408. Separate OM Storage initialization from OzoneManager

### PR DESCRIPTION
**Pull request by fapifta**
## What changes were proposed in this pull request?
The changeset is the first step of a refactoring effort around OzoneManager to clean up protobuf related code from OzoneManager and high level classes encapsulate this to one class per protocol if possible. With that on the long run, it helps to cleanup read path related code as well around XCeiverClientManager but this particular change is really really far from that point of the code.

The elements of the changeset:
- Extract Ozone Manager Storage initialization from OzoneManager class
- with that exctract all the SCM client protocol call related code from OzoneManager, to have a common place to use from the Storage initialiser code, and form OzoneManager itself.
- clear up unused code from OzoneManager after that
- fix test dependencies and set them to use the new code.

Steps that should come after this around the changed code:
- clear out the ScmClient class from OzoneManager and create and use it where it is really used
- add the methods to the ScmClient class that are used from the two protocol related class that is now returned by the ScmClient, and encapsulate protobuf there.
I separated this to two different steps, as the main part here was to separate OM Storage init, and common codes used by the storage init, and OM.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-2408

## How was this patch tested?
Ran JUnit tests locally, as this is a refactoring, I just actualised the test code to the proposed codebase, and ran the tests locally. Few timeout related tests failed, but they do not seem to be even related to the changes, we will see.

### CODE REVIEW

**Comment by anuengineer** [comment]
I am getting a compilation error on the msater. I know the build passed here, perhaps the patch was not applied to the latest trunk.

`/hadoop-ozone/ozone-manager/src/main/java/org/apache/hadoop/ozone/om/init/OzoneManagerInitializer.java:[38,58] incompatible types: org.apache.hadoop.ozone.om.init.SecurityInitializer cannot be converted to org.apache.hadoop.ozone.om.init.OzoneManagerInitializer`


Here is where my master branch is at:

commit 615571ec80eb148e2294c7cfee74e5b3ffc364b4 (HEAD -> master, origin/master, origin/HEAD)
Author: Doroszlai, Attila <6454655+adoroszlai@users.noreply.github.com>
Date:   Wed Nov 6 10:10:30 2019 +0100

    HDDS-2270. Avoid buffer copying in ContainerStateMachine.loadSnapshot/persistContainerSet (#118)

**Comment by fapifta** [comment]
Iteresting, I have renamed the OzoneManagerInitializer class to OzoneManagerStorageInitializer at the second commit on my branch which was based on the same commit.
The branch should not contain OzoneManagerInitializer anymore.

**Comment by adoroszlai** [comment]
> I am getting a compilation error on the msater. I know the build passed here, perhaps the patch was not applied to the latest trunk.

Same here.  Solution @anuengineer: download and apply [`diff`](https://github.com/apache/hadoop-ozone/pull/121.diff), not [`patch`](https://github.com/apache/hadoop-ozone/pull/121.patch).

**Comment by fapifta** [comment]
Test failures are related to the changes, I would need to look into the changeset before going forward.

**Comment by fapifta** [comment]
I think I have found the problem with the secure test failures, let's see how it goes, initial testing of ozonesecure-mr is promising, I have updated the PR to see the rest.

**Comment by fapifta** [comment]
There should be one test failure remaining after these fixes as I hope, which is the TestOzoneRpcClientWithRatis failure in TestOzoneRpcClientAbstract.testDeletedKeyForGDPR, which is unrelated to the changes, and seems to be a timing issue between the delete call and the actual handling of the deletion, this produces a failure for me locally with the master (at commit a6f80c096b5320f50b6e9e9b4ba5f7c7e3544385) as well.

I assume the timing problem because if I put a 500ms sleep into TestOzoneRpcClientAbstract.java:2796 the test finishes green, but I have not evaluated whether this would be the good solution to fix the test.

**Comment by fapifta** [comment]
After downloading and opening https://raw.githubusercontent.com/elek/ozone-ci-03/master/pr/pr-hdds-2408-kr8zj/acceptance/summary.html it seems that there were no test failure in acceptance tests themselves I am not sure what failed exactly.

**Comment by fapifta** [comment]
TestOzoneManagerHA and TestSecureOzoneCluster is still failing because of the changes as it seems from the results, looking into it further.

**Comment by adoroszlai** [comment]
Thanks @fapifta for working on this.  I would like to suggest closing this PR for now, and opening a new one when it's ready for review.

**Comment by fapifta** [comment]
I aggree Attila, I will work on this in the near term, and add a new PR when ready ;)

**Pull request closed without merging**
