### PR TITLE
HDDS-3504. Topology Test is Intermitent. Reduce container size to 256MB and blocksize to 64MB

### PR DESCRIPTION
**Pull request by sodonnel**
## What changes were proposed in this pull request?

The network-topology acceptance test was recently disabled as it was failing intermittently. Looking at the failure logs, it seems to be related to space constraints in the CI environments, as the datanodes are unable to reserve enough space to create a container eg:

Caused by: org.apache.hadoop.util.DiskChecker$DiskOutOfSpaceException: Out of space: The volume with the most available space (=965574656 B) is less than the container size (=1073741824 B).

To see if we can stabilize it again, I have reduced the container size to 200MB and enabled the test again in this PR.

## What is the link to the Apache JIRA

HDDS-3504

## How was this patch tested?

Existing tests

### CODE REVIEW

**Comment by sodonnel** [comment]
The topology acceptance test failed with:

```
2020-05-01 11:14:20,642 [pool-2-thread-1] ERROR freon.RandomKeyGenerator: Exception while adding key: key-0-60514 in bucket: bucket-0-75014 of volume: vol-0-57201.
INTERNAL_ERROR org.apache.hadoop.ozone.om.exceptions.OMException: Unsupported block size: 268435456
	at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.handleError(OzoneManagerProtocolClientSideTranslatorPB.java:816)
	at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.openKey(OzoneManagerProtocolClientSideTranslatorPB.java:807)
	at org.apache.hadoop.ozone.client.rpc.RpcClient.createKey(RpcClient.java:673)
	at org.apache.hadoop.ozone.client.OzoneBucket.createKey(OzoneBucket.java:326)
	at org.apache.hadoop.ozone.freon.RandomKeyGenerator.createKey(RandomKeyGenerator.java:696)
	at org.apache.hadoop.ozone.freon.RandomKeyGenerator.access$1100(RandomKeyGenerator.java:87)
	at org.apache.hadoop.ozone.freon.RandomKeyGenerator$ObjectCreator.run(RandomKeyGenerator.java:614)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I did not realise we had a block size that needs to be less than the container size.

**Comment by vivekratnavel** [comment]
@sodonnel Can we re-trigger the tests to get a green run? I think the integration test failure is not related to the change, but still, we need a green CI run to merge. Thanks!

**Comment by sodonnel** [comment]
@vivekratnavel Thanks for the review. I have just triggered another build, but please hold off on merging this change. I want to run the build 5 to 10 times to see if the acceptance tests stay stable with this change, as the topology test was unstable prior to the change.

**Comment by sodonnel** [comment]
This has been run 12 times now. We had several failures on IT tests (unrelated to this change) and we have had one failure on Acceptance, but it was not the topology change:

```
Output:  /tmp/smoketest/ozonesecure/result/robot-ozonesecure-ozonesecure-recon-scm.xml
ls: /var/log/hadoop: No such file or directory
ls: cannot access /var/log/hadoop: No such file or directory
```

I think this is as stable as it can get before we commit and see how it goes over time.

@vivekratnavel  @adoroszlai Are you happy for me to commit this one at this stage?

**Comment by vivekratnavel** [comment]
@sodonnel I am happy to merge this change! +1

**Pull request merged**
