### PR TITLE
HDDS-3241. Invalid container reported to SCM should be deleted.

### PR DESCRIPTION
**Pull request by linyiqun**
## What changes were proposed in this pull request?
SCM takes delete action for invalid container that reported by Datanodes.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3241

## How was this patch tested?
Run mvn test.

### CODE REVIEW

**Comment by elek** [comment]
Note: see the discussion in the jira: https://issues.apache.org/jira/browse/HDDS-3241

**Comment by linyiqun** [comment]
Addressed your comments now, @elek .

**Comment by linyiqun** [comment]
Thanks @elek  for the review.
From the latest CI result, only checkstyle issues exists, push additional commit to fix remaining checkstyle issues.

**Comment by linyiqun** [comment]
The CI result shows green CI now, :).

**Comment by elek** [comment]
Merged to the master. Thanks the contribution @linyiqun and the review @dineshchitlangia

**Pull request closed without merging**
