### PR TITLE
HDDS-1993. Merge OzoneManagerRequestHandler and OzoneManagerHARequest…

### PR DESCRIPTION
**Pull request by bharatviswa504**
## What changes were proposed in this pull request?

Merge HARequestHandler and non-HA request handler.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-1993

## How was this patch tested?

Ran a few integration tests which execute this code path.

### CODE REVIEW

**Comment by hanishakoneru** [comment]
Thanks @bharatviswa504 for working on this.
LGTM. +1.
What do you think of having the similar structure for ReadRequests as we have for WriteRequests?

**Comment by bharatviswa504** [comment]
> What do you think of having the similar structure for ReadRequests as we have for WriteRequests?

Do you mean to have their own request classes or not sure if this is what you are suggesting?

**Comment by hanishakoneru** [comment]
Yes.. They can have their own request classes extending a parent ReadRequest class and override handleReadRequest() method. It was just a thought. 
I am +1 for this PR. Ee can merge this and if you agree open a newbie Jira for the above.

**Comment by bharatviswa504** [comment]
> Yes.. They can have their own request classes extending a parent ReadRequest class and override handleReadRequest() method. It was just a thought.
> I am +1 for this PR. Ee can merge this and if you agree open a newbie Jira for the above.

Ya it is a good suggestion, but for read requests as we can use same code, no work is done in this area. But to be in a similar structure with write requests we can do that.

**Comment by bharatviswa504** [comment]
Thank You @hanishakoneru for the review.

**Pull request merged**
