### PR TITLE
HDDS-4067. Implement toString for OMTransactionInfo

### PR DESCRIPTION
**Pull request by amaliujia**
## What changes were proposed in this pull request?

To help debugging, It would be helpful to print actual transaction info by toString().

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4067

## How was this patch tested?

N/A

### CODE REVIEW

**Comment by amaliujia** [comment]
R: @bharatviswa504

**Comment by amaliujia** [comment]
@cxorm 

Thanks for helping trigger CI check! Can you tell me how to trigger a new CI (my first time to contribute to Ozone) so I can do myself?

**Comment by adoroszlai** [comment]
> Can you tell me how to trigger a new CI

```
git commit --allow-empty -m 'trigger new CI check' && git push
```

>  (my first time to contribute to Ozone)

Welcome. :)

**Comment by amaliujia** [comment]
friendly ping @bharatviswa504

**Comment by bharatviswa504** [comment]
Thank You @amaliujia for the contribution.

**Pull request merged**
