### PR TITLE
HDDS-2983. Acceptance test failures due to lack of disk space

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Reduce default number of containers and maximum container size in acceptance tests to avoid disk out of space errors.

https://issues.apache.org/jira/browse/HDDS-2983

## How was this patch tested?

Acceptance test run:

https://github.com/adoroszlai/hadoop-ozone/runs/427567308

It only failed due to HDDS-2977, which is being fixed in #527.

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
Merged HDDS-2977 and restart a test run.

**Comment by xiaoyuyao** [comment]
Thanks @adoroszlai for working on it. Fix LGTM, +1. I will merge it shortly.

**Comment by adoroszlai** [comment]
Thanks @xiaoyuyao for reviewing and committing it.

**Pull request merged**
