### PR TITLE
HDDS-4324. Add important comment to ListVolumes logic

### PR DESCRIPTION
**Pull request by lamber-ken**
## What changes were proposed in this pull request?

when execute `ozone sh volume ls` command only once, but the the statistics of list request is 2.

After delved into logic, it may not a bug. It's better add this comment.

image

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4234

image

### CODE REVIEW

**Comment by lamber-ken** [comment]
help

**Comment by lamber-ken** [comment]
hi @nandakumar131, can you have a review? refer to https://github.com/apache/hadoop-ozone/pull/385

**Comment by lamber-ken** [comment]
hi @elek can you have a review? refer to #385

**Review by elek — APPROVED** [review]
+1 LGTM

To be honest, I was not familiar with this part of the code. But with the help of this hint, and with checking the code understood it, and comment seems to be true.

**Pull request merged**
