### PR TITLE
HDDS-2562. Handle InterruptedException in DatanodeStateMachine

### PR DESCRIPTION
**Pull request by dineshchitlangia**
## What changes were proposed in this pull request?

Addressed sonar violations - handle InterruptedException, removed unused variables etc.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-2562

## How was this patch tested?

Clean build, sonar & checkstyle in local.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@dineshchitlangia Thanks for working on this! Can we re-trigger CI to get a green run?

**Comment by dineshchitlangia** [comment]
@vivekratnavel Thanks for reviewing.
There seems to be some os errors in the acceptance tests and some tests were cancelled.

I have re-triggered a few time but still get the same issues in different stages.
Let me investigate a bit more and get back.

**Comment by dineshchitlangia** [comment]
Most failures are due to 
`[7.002s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.`

This PR had no issues in my fork, appreciate any thoughts/hints - @elek  / @adoroszlai

**Comment by dineshchitlangia** [comment]
Thanks @vivekratnavel & @arp7 for review.

**Pull request merged**
