### PR TITLE
WIP:HDDS-3666. Fix delete container cli failed.

### PR DESCRIPTION
**Pull request by maobaolong**
## What changes were proposed in this pull request?

Bugfix: Delete container failed

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3666

## How was this patch tested?

```bash
bin/ozone admin container delete <ContainerID>
bin/ozone admin container info  <ContainerID>
Container with id #<ContainerID> not found.
```

### CODE REVIEW

**Comment by maobaolong** [comment]
@adoroszlai Thank you for telling me, close this PR.

**Comment by elek** [comment]
What is the state of this PR? If I understood well we need this change but requires a cleanup on this PR...

**Comment by maobaolong** [comment]
@elek I'm not working on this PR recently. let me mark it as WIP.

**Pull request closed without merging**
