### PR TITLE
HDDS-2291. Exclude OM HA tests from the acceptance tests.

### PR DESCRIPTION
**Pull request by elek**
## What changes were proposed in this pull request?

HDDS-2291 introduced a new acceptance test but this is unstable. I propose to disable it until  HDDS-2454 is committed and tested.

## What is the link to the Apache JIRA

Didn't create separated issue (HDDS_2291 is the original). Opening this PR as a test.

## How was this patch tested?

Let see what will be the CI status.

### CODE REVIEW

**Comment by adoroszlai** [comment]
💚

**Comment by elek** [comment]
TLDR; To fix all the unit/acceptance issues:

 1. HDDS-2034 should be reverted (#202 )
 2. OM HA tests should be disabled (be94c4885f9f9bcb9301575ed2ad401304163f16)
 3. HDDS-25221 (#206) should be merged (thanks to @adoroszlai)

**Comment by adoroszlai** [comment]
And to fix most integration tests, we need #180, #207 and [HDDS-2491](https://issues.apache.org/jira/browse/HDDS-2491).

**Comment by elek** [comment]
Created HDDS-2533 for a new pull request:

 1. I will commit HDDS-2521
 2. Instead of reverting HDDS-2034 will disable the failing test
 3. Will disable the failing OM HA tests.

**Pull request closed without merging**
