### PR TITLE
HDDS-2565. Handle InterruptedException in VolumeSet

### PR DESCRIPTION
**Pull request by cxorm**
## What changes were proposed in this pull request?
Re-Interrupt when catching the ```InterruptedException```.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-2565

## How was this patch tested?
UT Updating to validate the behavior.

### CODE REVIEW

**Comment by elek** [comment]
FYI: `/retest` is not working (yet) with github actions. Just push an empty commit (`git commit --allow-empty -m "..."`) and push it.

**Comment by cxorm** [comment]
Thanks @elek for the information.

**Comment by cxorm** [comment]
The acceptance test failure does not seem to be related to this patch.

**Comment by cxorm** [comment]
Thanks @elek for the review and commit.

**Pull request closed without merging**
