### PR TITLE
HDDS-4280. Document notable configurations for Recon.

### PR DESCRIPTION
**Pull request by linyiqun**
## What changes were proposed in this pull request?

Document notable configurations for Recon

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4280

## How was this patch tested?

Github branch build test.

### CODE REVIEW

**Review by vivekratnavel — APPROVED** [review]

**Comment by vivekratnavel** [comment]
@adoroszlai Thanks for working on this!

**Review by avijayanhwx — APPROVED** [review]
Thanks for adding this @linyiqun.

Can we add a follow up JIRA to fix this inconsistent config key (recon.om.snapshot.task.interval.delay) ?

**Comment by adoroszlai** [comment]
> Can we add a follow up JIRA to fix this inconsistent config key (recon.om.snapshot.task.interval.delay) ?

@avijayanhwx if you mean it should be prefixed with `ozone.`, please note there are few other similar keys:

```
hadoop-hdds/common/src/main/resources/ozone-default.xml
2318:    <name>recon.om.connection.request.timeout</name>
2327:    <name>recon.om.connection.timeout</name>
2336:    <name>recon.om.socket.timeout</name>
2345:    <name>recon.om.snapshot.task.initial.delay</name>
2353:    <name>recon.om.snapshot.task.interval.delay</name>
2361:    <name>recon.om.snapshot.task.flush.param</name>
```

**Comment by linyiqun** [comment]
>Can we add a follow up JIRA to fix this inconsistent config key (recon.om.snapshot.task.interval.delay) ?

Hi @avijayanhwx , I also find there is more other ozone recon keys not  prefixed with ozone like @adoroszlai  mentioned. Maybe we should fix them all in a separate JIRA.

**Comment by avijayanhwx** [comment]
> > Can we add a follow up JIRA to fix this inconsistent config key (recon.om.snapshot.task.interval.delay) ?
> 
> Hi @avijayanhwx , I also find there is more other ozone recon keys not prefixed with ozone like @adoroszlai mentioned. Maybe we should fix them all in a separate JIRA.

Yes, @linyiqun I did not mean that config key name changes are related to your fix. I just noticed that bad name, and wanted to track it. I will create the JIRA myself.

**Comment by avijayanhwx** [comment]
Thanks for the review @vivekratnavel.

**Comment by linyiqun** [comment]
Thanks @vivekratnavel  and @avijayanhwx  for the review and merge!

**Pull request merged**
