### PR TITLE
HDDS-2866. Intermittent failure in TestOzoneManagerRocksDBLogging

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Swap positive and negative test cases of RocksDB logging to avoid log messages from finalizer affecting the non-logging case.

https://issues.apache.org/jira/browse/HDDS-2866

## How was this patch tested?

Tested locally, as well as on branch with integration tests enabled:

```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 39.749 s - in org.apache.hadoop.ozone.om.TestOzoneManagerRocksDBLogging
```

https://github.com/adoroszlai/hadoop-ozone/runs/382195722

### CODE REVIEW

**Comment by adoroszlai** [comment]
@avijayanhwx @swagle please review

**Comment by avijayanhwx** [comment]
LGTM +1.

**Comment by xiaoyuyao** [comment]
Good catch. The fix LGTM, +1. I will merge it shortly.

**Comment by adoroszlai** [comment]
Thanks @avijayanhwx for the review, and @xiaoyuyao for reviewing and merging this.

**Pull request merged**
