### PR TITLE
HDDS-3614. Remove S3Table from OmMetadataManager.

### PR DESCRIPTION
**Pull request by bharatviswa504**
## What changes were proposed in this pull request?

Remove S3Table from OmMetadataManager, which are not used any more after HDDS-3385.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3614

## How was this patch tested?

Cleanup Jira.

### CODE REVIEW

**Comment by ChenSammi** [comment]
@bharatviswa504,  the patch overall looks good. 
The static final string "S3_TABLE" and it's usage in the addOMTablesAndCodecs is missed.

**Comment by bharatviswa504** [comment]
Thank You @ChenSammi for the review.
Addressed review comments.

**Comment by bharatviswa504** [comment]
Hi @adoroszlai 
To solve this incompatibility, it is said we shall use bind mounts, untill then using configurable volume for s3 gateway.

https://github.com/apache/hadoop-ozone/pull/915#issuecomment-630146061

Above is the link and refer to PR for discussion. 

If there is another alternative proposal on the table to use the information from table, I am fine with delaying it. Can you share what is the proposal and how do we use this table?

**Comment by captainzmc** [comment]
LGTM +1. The S3Table is no longer useful after HDDS-3385, and the original mapping relationship should not be needed.

**Pull request merged**
