### PR TITLE
HDDS-4264. Uniform naming conventions of Ozone Shell Options.

### PR DESCRIPTION
**Pull request by captainzmc**
## What changes were proposed in this pull request?

Current Shell command of Ozone, some use hump connection, some use '-' connection. We need to unify the naming conventions.
See the usage [documentation of Picocli](https://picocli.info/#command-methods), which use '-' connection more often. 
image

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-4264

## How was this patch tested?
UT has been fixed.

### CODE REVIEW

**Comment by captainzmc** [comment]
Hi @adoroszlai，Could you help review this PR?

**Comment by amaliujia** [comment]
+1 on unifying the name convention. 

Though not sure which name convention is better :) Would also want to hear suggestions from @adoroszlai

**Comment by amaliujia** [comment]
@captainzmc you might try `git commit --allow-empty -m 'trigger new CI check' && git push` to trigger CI which does not trigger PR change notification :-)

**Comment by adoroszlai** [comment]
Thanks for working on this @captainzmc.  Can you please resolve conflict with latest master when you get a chance?

**Comment by captainzmc** [comment]
> Thanks for working on this @captainzmc. Can you please resolve conflict with latest master when you get a chance?
Thanks for @adoroszlai 's reminding. I have solved the conflict. This PR can continue to be reviewed.

**Review by elek — APPROVED** [review]
(big) +1  

Thanks for the fix @captainzmc 

I really like that we started to follow the standard convention. (I use a lot of shell tools and camel case parameters always annoyed me).

And change seems to be backward compatible / safe (old aliases still work)

**Pull request merged**
