### PR TITLE
HDDS-2650 Fix createPipeline and make createPipeline CLI message based.

### PR DESCRIPTION
**Pull request by timmylicheng**
## What changes were proposed in this pull request?
#HDDS-2650 Make createPipeline CLI message based to fix after merge with master.

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-2650

(Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?
bash-4.2$ ozone scmcli pipeline list
Pipeline[ Id: 2aa5b959-8e9d-4c72-a6ef-ec30f00f1dca, Nodes: 53ab812b-6ec4-468b-861c-64d2a1445deb{ip: 192.168.32.2, host: ozone_datanode_1.ozone_default, networkLocation: /default-rack, certSerialId: null}, Type:RATIS, Factor:ONE, State:ALLOCATED, leaderId:null, CreationTimestamp1576579695167]
bash-4.2$ ozone scmcli pipeline create
bash-4.2$ ozone scmcli pipeline list
Pipeline[ Id: 2aa5b959-8e9d-4c72-a6ef-ec30f00f1dca, Nodes: 53ab812b-6ec4-468b-861c-64d2a1445deb{ip: 192.168.32.2, host: ozone_datanode_1.ozone_default, networkLocation: /default-rack, certSerialId: null}, Type:RATIS, Factor:ONE, State:OPEN, leaderId:53ab812b-6ec4-468b-861c-64d2a1445deb, CreationTimestamp1576579705686]
Pipeline[ Id: c34c276f-f187-4048-9e20-81188c24fe79, Nodes: 53ab812b-6ec4-468b-861c-64d2a1445deb{ip: 192.168.32.2, host: ozone_datanode_1.ozone_default, networkLocation: /default-rack, certSerialId: null}, Type:STAND_ALONE, Factor:ONE, State:OPEN, leaderId:null, CreationTimestamp1576579705686]

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

### CODE REVIEW

**Comment by ChenSammi** [comment]
Can you revert the previous HDDS-2650 commit and merge these two PR into one?

**Comment by timmylicheng** [comment]
> Can you revert the previous HDDS-2650 commit and merge these two PR into one? Cannnot commit the same JR twice.

I have included the revert commit and the new commit in this PR and I've updated the JIRA as well.

**Comment by timmylicheng** [comment]
testCloseContainerEventWithRati is fixed in https://github.com/apache/hadoop-ozone/pull/291/files

**Comment by ChenSammi** [comment]
Can we refine the message when pipeline cannot be allocated for some reason? 
bash-4.2$ ozone scmcli pipeline create -f THREE -t RATIS
Not enough healthy nodes to allocate pipeline. 3  datanodes required. Found 1
bash-4.2$ ozone scmcli pipeline create -f ONE -t RATIS  
Cannot create pipeline of factor 1 using 0 nodes. Used 1 nodes. Healthy nodes 1

**Comment by timmylicheng** [comment]
> Can we refine the message when pipeline cannot be allocated for some reason?
> bash-4.2$ ozone scmcli pipeline create -f THREE -t RATIS
> Not enough healthy nodes to allocate pipeline. 3 datanodes required. Found 1
> bash-4.2$ ozone scmcli pipeline create -f ONE -t RATIS
> Cannot create pipeline of factor 1 using 0 nodes. Used 1 nodes. Healthy nodes 1

https://issues.apache.org/jira/browse/HDDS-2756 is tracking logging issues. Will address there.

**Comment by ChenSammi** [comment]
+ 1,  will commit to the branch.

**Pull request merged**
