### PR TITLE
HDDS-3119. When ratis is enabled in OM, double Buffer metrics not get…

### PR DESCRIPTION
**Pull request by avijayanhwx**
…ting updated.

## What changes were proposed in this pull request?
Ozone Manager creates 2 instances of OzoneManagerDoubleMetrics, and the way Hadoop metrics2 works, the second one overwrites the first. In our case, it is the first instance that is on the Ratis write path. Fixed this issue by making sure there is only instance of OzoneManagerDoubleMetrics.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3119

## How was this patch tested?
Manually tested.

### CODE REVIEW

**Comment by bharatviswa504** [comment]
Can we avoid double instantiation of doublebuffer which is not required in OM, that will resolve this issue.

**Comment by avijayanhwx** [comment]
Unit test failure TestSCMPipelineBytesWrittenMetrics is not related to this patch.

**Comment by bharatviswa504** [comment]
There is already a Jira I have opened for the same test.

**Comment by adoroszlai** [comment]
> There is already a Jira I have opened for the same test.

Me too. :)

**Pull request merged**
