### PR TITLE
HDDS-3432. Enable TestBlockDeletion test cases.

### PR DESCRIPTION
**Pull request by lokeshj1703**
## What changes were proposed in this pull request?

Enable block deletion test

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3432

## How was this patch tested?

Enables a UT

### CODE REVIEW

**Comment by lokeshj1703** [comment]
Ran a workflow on the branch.
https://github.com/lokeshj1703/hadoop-ozone/actions?page=1&query=workflow%3Ait-client
The test failed 5 times out of 100.

**Comment by adoroszlai** [comment]
Thanks @lokeshj1703 for working on this.  3/20 runs failed with two different problems:

1. assertion failure at `TestBlockDeletion.verifyPendingDeleteEvent(TestBlockDeletion.java:275)`
2. timeout at `TestBlockDeletion.testBlockDeletion(TestBlockDeletion.java:200)`

https://github.com/adoroszlai/hadoop-ozone/runs/808704334

**Comment by lokeshj1703** [comment]
Thanks @adoroszlai for verifying! I have pushed a commit which fixes the timeout issue. For the time being I have ignored the verifyPendingDeleteEvent check. I will need to think of another way for that test.

FYI - I had enabled a workflow for this test at https://github.com/lokeshj1703/hadoop-ozone/actions?query=workflow%3ATestBlockDeletion2. I am not sure if it takes the latest changes from the branch though.

**Comment by adoroszlai** [comment]
Thanks @lokeshj1703 for updating the patch.  1/20 runs still failed with timeout: https://github.com/adoroszlai/hadoop-ozone/runs/814060939

**Comment by lokeshj1703** [comment]
@adoroszlai Thanks for verifying! The test failed in the 20th iteration and it failed because of appendEntries timeout. 
But I can see other failures like https://github.com/lokeshj1703/hadoop-ozone/runs/812429922?check_suite_focus=true in my workflow. I am currently working on this failure. Will update once I have all green runs except the appendEntries timeout issue.

**Comment by lokeshj1703** [comment]
@adoroszlai The workflow is now green. There were 2 failures in around 70 runs. One where cluster start timed out at waitForClusterToBeReady and another with appendEntriesTimeout.

**Comment by adoroszlai** [comment]
Thanks @lokeshj1703 for updating the patch.  I still see 1/20 failure due to timeout at `TestBlockDeletion.testBlockDeletion(TestBlockDeletion.java:174)`.

https://github.com/adoroszlai/hadoop-ozone/runs/844624809

**Comment by lokeshj1703** [comment]
@adoroszlai Thanks for verifying! I see appendEntries timeout in the particular run. The blocks creation in all the datanodes timed out in the run. The failure occurs in iteration 12.

**Pull request closed without merging**
