### PR TITLE
HDDS-3784. Use matrix build for integration test

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Reduce code duplication in Ozone's GitHub Actions workflow definitions by using matrix build for integration tests instead of individual jobs.

https://issues.apache.org/jira/browse/HDDS-3784

## How was this patch tested?

Verified that multiple integration test runs with different profiles were executed in parallel:

https://github.com/adoroszlai/hadoop-ozone/runs/761852962
https://github.com/adoroszlai/hadoop-ozone/runs/761852971

They each uploaded separate artifacts.

Verified that coverage check waits for all of these.

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@adoroszlai I like this matrix approach. Its much cleaner now. Thanks for working on this! Can you merge the latest master with this branch since recent commits involve changes in the workflow? It will be good to see another run here before merging. Thanks!

**Comment by adoroszlai** [comment]
Thanks @vivekratnavel for the review.  I have merged latest workflow-related changes from `master`.

**Comment by vivekratnavel** [comment]
@adoroszlai Thanks for the merge! The CI run looks good. I am merging it now.

**Comment by adoroszlai** [comment]
Thanks @vivekratnavel for reviewing and merging it.

**Pull request merged**
