### PR TITLE
HDDS-2924. Fix Pipeline#nodeIdsHash collision issue.

### PR DESCRIPTION
**Pull request by xiaoyuyao**
## What changes were proposed in this pull request?
Change to use the set of datanodes that form the pipeline to detect overlapped pipeline allocation. 
Remove the nodeIdHash that could collide. 

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-2924

## How was this patch tested?
unit tests

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
The checkstyle issue should be fixed in next commit. However, there is an issue when interop multi-raft with rackawareness, which is detected by the topology acceptance test. It is not related to this change but I will look into it.

**Comment by timmylicheng** [comment]
> The checkstyle issue should be fixed in next commit. However, there is an issue when interop multi-raft with rackawareness, which is detected by the topology acceptance test. It is not related to this change but I will look into it.

I have a JIRA https://issues.apache.org/jira/browse/HDDS-2923 to fix rack awareness issue,. We may track there.

**Comment by xiaoyuyao** [comment]
Thanks @timmylicheng. In this one, I include some minor fixes around PipelinePlacementPolicy to cover the non-fallback case where we have enough nodes on different racks but are not chosen properly. 

Agree, we should have the fall back fix in HDDS-2923.

**Comment by anuengineer** [comment]
That is a pretty smart fix. You are absolutely right, we need no magic to find if a three node set is equal to another. +1, once @xiaoyuyao  is happy.

**Comment by xiaoyuyao** [comment]
push the correct rebase.

**Comment by xiaoyuyao** [comment]
Thanks @anuengineer and @timmylicheng for the reviews. I will merge it shortly.

**Pull request merged**
