### PR TITLE
HDDS-2278. Run S3 test suite on OM HA cluster.

### PR DESCRIPTION
**Pull request by bharatviswa504**
Add a docker compose OM HA cluster with S3.
Run the S3 test suite on the OM HA cluster.
https://issues.apache.org/jira/browse/HDDS-2278

### CODE REVIEW

**Comment by elek** [comment]
UPDATE: it's failing during my local test all the time. the ozones3 is working but not the new tests. Let's try to request a new test run...

**Comment by bharatviswa504** [comment]
Thank You @elek for the review.
I see newly acceptance tests are passing. Let me know if you still see errors in your local run.

**Comment by bharatviswa504** [comment]
> +1 thanks the patch @bharatviswa504
> 
> Note: While I am happy to have more and more environments, I feel that it's harder and harder to manage them and some of them are confusing. I am thinking about to merge some of the environments, for example include s3 in the simple ozone (and ozone-om-ha) and delete ozone-s3.
> 
> S3 doesn't have huge resource requirement and very core of our provided functionality.
> 
> This is not related to this patch (as this patch follows the current practice) but I am very interested about your opinion.

Yes, I am with you on this, S3 now became core functionality, we don't need a separate environment for it, we can include S3 in Ozone compose. And also this helps in reducing run time of our acceptance test suite.

**Comment by bharatviswa504** [comment]
@elek can we commit this or still some issues you are seeing?

**Comment by elek** [comment]
I see a problem locally, which is passed on the server. Don't know what is the exact problem...

**Comment by adoroszlai** [comment]
@bharatviswa504 @elek I think the problem is with the upgraded Ratis (https://github.com/apache/hadoop-ozone/pull/26#pullrequestreview-302565890).  Leader election problem affects OM HA.

1. The pull request [source branch](https://github.com/bharatviswa504/hadoop-ozone/commits/HDDS-2278) is based on 920dde90, which precedes Ratis upgrade 546e36bf.  Test passes locally when checking out this branch.  This is what CI is testing.
2. Applying the patch on current master (2529cee1), the test fails locally.  Log is full of leader election attempts:

```
om1_1       | 2019-10-18 15:55:51,883 INFO impl.RaftServerImpl: om1@group-562213E44849: changes role from CANDIDATE to FOLLOWER at term 3601 for DISCOVERED_A_NEW_TERM
...
om1_1       | 2019-10-18 15:55:52,026 INFO impl.RaftServerImpl: om1@group-562213E44849: changes role from  FOLLOWER to CANDIDATE at term 3601 for changeToCandidate
...
om1_1       | 2019-10-18 15:55:52,038 INFO impl.RaftServerImpl: om1@group-562213E44849: changes role from CANDIDATE to FOLLOWER at term 3602 for DISCOVERED_A_NEW_TERM
```

**Comment by bharatviswa504** [comment]
Thank You @adoroszlai for the analysis.
I will wait until we upgrade to the latest Ratis version to commit this.

**Comment by bharatviswa504** [comment]
Rebased with the latest master(after ratis version upgrade)

**Comment by bharatviswa504** [comment]
Newly added tests are passing, test failures are not related to this patch.

**Comment by dineshchitlangia** [comment]
Thanks @elek and @adoroszlai for reviews. Thanks @bharatviswa504 for this contribution. Committed this change.

**Pull request merged**
