### PR TITLE
HDDS-3262. Fix TestOzoneRpcClientWithRatis.java.

### PR DESCRIPTION
**Pull request by bshashikant**
What changes were proposed in this pull request?
With RATIS-840 incorporated in ozone, the test is expected to work. Re-enabling it here.

What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3262

How was this patch tested?
Will Verify it in the CI runs.

### CODE REVIEW

**Comment by bshashikant** [comment]
Filed https://issues.apache.org/jira/browse/HDDS-3789 to track the unit test failure.

**Comment by bharatviswa504** [comment]
+1 to get this in BTW.
@bshashikant how this test is related to RATIS-840? 
just trying to understand the issue, I believe this test is added by HDDS-1121. Not sure If I am missing something here.

**Comment by bshashikant** [comment]
> +1 to get this in BTW.
> @bshashikant how this test is related to RATIS-840?
> just trying to understand the issue, I believe this test is added by [HDDS-1121](https://issues.apache.org/jira/browse/HDDS-1121). Not sure If I am missing something here.

Thanks @bharatviswa504 . Without Ratis-840, the write/watch requests on ratis were timing out leading to many test failures in this class. Now that , its fixed, we can reenable the tests here.

**Comment by bshashikant** [comment]
Thanks @bharatviswa504 for the review. I have committed this.

**Pull request merged**
