### PR TITLE
Update pull_request_template.md

### PR DESCRIPTION
**Pull request by avijayanhwx**
Update Pull Request Template

### CODE REVIEW

**Comment by anuengineer** [comment]
We need a JIRA number to commit anything into the branch. So you will have to file a JIRA and refer to that in the pull request. and it might be a good idea to add needing a link to the original JIRA also.

**Comment by adoroszlai** [comment]
This was already done in #5, was it lost during the forced update?

**Comment by vivekratnavel** [comment]
Yes, #5 is not merged yet. We can close this PR and merge #5.

**Comment by avijayanhwx** [comment]
Thanks @adoroszlai. I will close this.

**Pull request closed without merging**
