### PR TITLE
HDDS-4074. [OFS] Implement AbstractFileSystem for RootedOzoneFileSystem

### PR DESCRIPTION
**Pull request by adoroszlai**
## What changes were proposed in this pull request?

Add `RootedOzFs`, implementation of `AbstractFileSystem` for `RootedOzoneFileSystem`.  This will allow running MapReduce tests with OFS.

Extracted from #1088.  Also applied the fix from HDDS-3482.

https://issues.apache.org/jira/browse/HDDS-4074

## How was this patch tested?

Executed `ozone-mr` acceptance tests locally:

```
export OZONE_TEST_SELECTOR='ozone-mr\|hadoop..'
hadoop-ozone/dev-support/checks/acceptance.sh
```

after tweaking config and MR test to use `ofs` instead of `o3fs`:

```diff
diff --git hadoop-ozone/dist/src/main/compose/ozone-mr/common-config hadoop-ozone/dist/src/main/compose/ozone-mr/common-config
index 46e752731..91588aa77 100644
--- hadoop-ozone/dist/src/main/compose/ozone-mr/common-config
+++ hadoop-ozone/dist/src/main/compose/ozone-mr/common-config
@@ -30,7 +30,8 @@ OZONE-SITE.XML_hdds.datanode.dir=/data/hdds
 HDFS-SITE.XML_dfs.datanode.address=0.0.0.0:1019
 HDFS-SITE.XML_dfs.datanode.http.address=0.0.0.0:1012

-CORE-SITE.xml_fs.defaultFS=o3fs://bucket1.volume1/
+CORE-SITE.xml_fs.defaultFS=ofs://om/volume1/bucket1/
+CORE-SITE.XML_fs.ofs.impl=org.apache.hadoop.fs.ozone.RootedOzoneFileSystem

 MAPRED-SITE.XML_mapreduce.framework.name=yarn
 MAPRED-SITE.XML_yarn.app.mapreduce.am.env=HADOOP_MAPRED_HOME=$HADOOP_HOME
diff --git hadoop-ozone/dist/src/main/smoketest/mapreduce.robot hadoop-ozone/dist/src/main/smoketest/mapreduce.robot
index 654dd49c6..e2dfd11a1 100644
--- hadoop-ozone/dist/src/main/smoketest/mapreduce.robot
+++ hadoop-ozone/dist/src/main/smoketest/mapreduce.robot
@@ -39,5 +39,5 @@ Execute PI calculation
 Execute WordCount
                     ${exampleJar}    Find example jar
                     ${random}        Generate Random String  2   [NUMBERS]
-                    ${output} =      Execute                 yarn jar ${exampleJar} wordcount o3fs://bucket1.volume1/key1 o3fs://bucket1.volume1/key1-${random}.count
+                    ${output} =      Execute                 yarn jar ${exampleJar} wordcount ofs://om/volume1/bucket1/key1 ofs://om/volume1/bucket1/key1-${random}.count
                     Should Contain   ${output}               completed successfully

```

Regular CI:
https://github.com/adoroszlai/hadoop-ozone/runs/975699201

### CODE REVIEW

**Comment by smengcl** [comment]
@elek Would you like to take a look at this?

**Review by elek — APPROVED** [review]
+1 Merging it

Thanks @adoroszlai and @smengcl

**Comment by adoroszlai** [comment]
Thanks @elek for reviewing and merging it.

Unfortunately GitHub UI merge assigned me as author of the commit, sorry @smengcl about that.

**Comment by smengcl** [comment]
@adoroszlai No worries! Thanks you for creating this PR )

**Pull request merged**
