### PR TITLE
HDDS-3020. Fix TestOzoneClientRetriesOnException.java

### PR DESCRIPTION
**Pull request by bshashikant**
## What changes were proposed in this pull request?
It fixes the unit test TestOzoneClientRetriesOnException#testMaxRetriesByOzoneClient by fixing the exception message in KeyOutputStream.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3020

## How was this patch tested?
The TestOzoneClientRetriesOnException tests are working successfully.

### CODE REVIEW

**Comment by adoroszlai** [comment]
A different failure on next 20th run:

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 84.073 s <<< FAILURE! - in org.apache.hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException
[ERROR] testMaxRetriesByOzoneClient(org.apache.hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException)  Time elapsed: 39.181 s  <<< FAILURE!
java.lang.AssertionError: Expected exception not thrown
  ...
  at org.apache.hadoop.ozone.client.rpc.TestOzoneClientRetriesOnException.testMaxRetriesByOzoneClient(TestOzoneClientRetriesOnException.java:218)
```

https://github.com/adoroszlai/hadoop-ozone/runs/455545015
log/output: https://github.com/adoroszlai/hadoop-ozone/suites/468331010/artifacts/2018291

**Comment by adoroszlai** [comment]
Crashed again on merge to `master`: https://github.com/apache/hadoop-ozone/runs/457338931

May need some follow-up fix.

**Comment by bshashikant** [comment]
> Crashed again on merge to `master`: https://github.com/apache/hadoop-ozone/runs/457338931
> 
> May need some follow-up fix.

I don't think its happening because of the test.

**Comment by adoroszlai** [comment]
> I don't think its happening because of the fix for the test.

I didn't mean the crash was caused by the fix, rather an existing problem, probably affecting other tests, too.

**Pull request merged**
