### PR TITLE
HDDS-3441. Enable TestKeyManagerImpl test cases.

### PR DESCRIPTION
**Pull request by aryangupta1998**
## What changes were proposed in this pull request?

Fixed testCheckAccessForFileKey() and testCheckAccessForNonExistentKey().

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3441

## How was this patch tested?

Tested Manually.

### CODE REVIEW

**Comment by aryangupta1998** [comment]
Hi @xiaoyuyao 
Can you please review this?

**Review by elek — APPROVED** [review]
+1

Tested locally and I can confirm that it's failing without the patch.

It's not a flaky test but one with bug, which is fixed. Nice catch.

Will merge it after the build.

**Comment by elek** [comment]
LGTM (== Looks Green To Me)

**Pull request merged**
