### PR TITLE
HDDS-3453. Use UrlConnectionFactory to handle HTTP Client SPNEGO for …

### PR DESCRIPTION
**Pull request by xiaoyuyao**
…ozone components.

## What changes were proposed in this pull request?

Recon to connect OM dbcheckpoint endpoint with spnego support. 

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3453

## How was this patch tested?
Acceptance tests (positive and negative) added for spnego enabled cluster.

### CODE REVIEW

**Comment by xiaoyuyao** [comment]
My original plan is to fix the OM side separately as that needs secure HA OM docker-compose to test it (I don't believe we have one yet).

**Comment by avijayanhwx** [comment]
LGTM +1

**Comment by vivekratnavel** [comment]
@xiaoyuyao Can you please rebase on latest master to retrigger tests and get a green CI run?

**Comment by xiaoyuyao** [comment]
New commit with 
1. fix the OzoneManagerSnapshotProvider, 
2. added a secure ozone manager ha docker-compose 
3. add secure ozone manager ha acceptance tests.

**Pull request merged**
