### PR TITLE
HDDS-1701. Move dockerbin script to libexec.

### PR DESCRIPTION
**Pull request by cxorm**
## What changes were proposed in this pull request?

Relocate the docker scripts in dist.
(from ```bin/docker/``` to ```libexec/```)

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-1701

## How was this patch tested?

Ran ```test-all.sh``` under ```$OZONE_HOME/compose/``` in distribution.

### CODE REVIEW

**Comment by cxorm** [comment]
When test-all.sh is ran in distribution, it works well.
But when it called by acceptance.sh, it fails.
We are looking for the cause.

**Comment by elek** [comment]
Seems to be working for me even with `acceptance.sh`. Let's try to retest.

**Comment by elek** [comment]
No idea what's wrong here, but I am not brave enough to commit it without understanding the reason of the acceptance test failure.

Let me try to find the root cause...

**Comment by cxorm** [comment]
> No idea what's wrong here, but I am not brave enough to commit it without understanding the reason of the acceptance test failure.
> 
> Let me try to find the root cause...

Yes, thanks @elek for the review.
We're going to find the root cause.

**Comment by elek** [comment]
Ok. I found the problem. The changed Dockerfile is used only to create images for k8s deployment.

To change the PATH in the ozone-runner image, a new PR should be created in hadoop-ozone-docker repository (ozone-runner branch):

https://github.com/apache/hadoop-docker-ozone/tree/runner-latest
 
Can you please create a new PR in that repository (with the same jira id) with adding the new path to this line: 

https://github.com/apache/hadoop-docker-ozone/blob/7619b7b7d1cc27629292f959d082c01e23ae8870/Dockerfile#L39

I will commit it + tag it --> It will create a new apache/ozone-runner image which can be used by updating `hadoop-ozone/dist/pom.xml`  (docker.ozone-runner.version)

**Comment by cxorm** [comment]
Wow, thanks @elek for the comment.
This comment help me a lot.
Fixed and send a PR in ```apache/hadoop-docker-ozone```.

**Comment by elek** [comment]
New ozone-runner is available: `apache/ozone-runner:20191107-1`  You can update the version in `hadoop-ozone/dist/pom.xml`

```
<docker.ozone-runner.version>20191106-1</docker.ozone-runner.version>
```

And (hopefully) the acceptance tests will be passed and ready to merge.

**Comment by cxorm** [comment]
Thanks @elek for all the help and reviews.

**Pull request closed without merging**
