### PR TITLE
HDDS-4137. Turn on the verbose mode of safe mode check on testlib

### PR DESCRIPTION
**Pull request by maobaolong**
## What changes were proposed in this pull request?

Turn on the verbose mode of safe mode check on testlib

## What is the link to the Apache JIRA

HDDS-4137

## How was this patch tested?

No need

### CODE REVIEW

**Review by adoroszlai — CHANGES_REQUESTED** [review]
This breaks `upgrade` acceptance test, as old version (0.5.0) tries to use new flag.  Please introduce a new variable in `hadoop-ozone/dist/src/main/compose/upgrade/versions/ozone-0.5.0.sh` and `hadoop-ozone/dist/src/main/compose/upgrade/versions/ozone-0.6.0.sh`, eg.:

```
export OZONE_SAFEMODE_STATUS_COMMAND='ozone scmcli safemode status'
```

and


```
export OZONE_SAFEMODE_STATUS_COMMAND='ozone admin safemode status --verbose'
```

respectively, then use the new variable in `testlib.sh`.

**Comment by maobaolong** [comment]
@adoroszlai Thanks very much for show me this tip, I think it can help me to pass the acceptance test.

**Comment by adoroszlai** [comment]
@maobaolong Thanks for updating the patch.  Sorry, I forgot that `OZONE_SAFEMODE_STATUS_COMMAND` needs to have a default value, so the following change is needed:

```diff
diff --git hadoop-ozone/dist/src/main/compose/testlib.sh hadoop-ozone/dist/src/main/compose/testlib.sh
index 24a7de3b1..228572fe2 100755
--- hadoop-ozone/dist/src/main/compose/testlib.sh
+++ hadoop-ozone/dist/src/main/compose/testlib.sh
@@ -63,7 +63,7 @@ find_tests(){
 ## @description wait until safemode exit (or 180 seconds)
 wait_for_safemode_exit(){
   # version-dependent
-  : ${OZONE_ADMIN_COMMAND:=admin}
+  : ${OZONE_SAFEMODE_STATUS_COMMAND:=ozone admin safemode status --verbose}

   #Reset the timer
   SECONDS=0
```

**Comment by maobaolong** [comment]
@adoroszlai Thank you for trigger CI checks for me, I see full green now, 😁. PTAL.

**Review by adoroszlai — APPROVED** [review]
Thanks @maobaolong for the contribution.  This should help in debugging intermittent failures due to SCM not coming out of safe mode.

**Pull request merged**
