### PR TITLE
HDDS-3246. Include OM hostname info in getserviceroles subcommand of OM CLI

### PR DESCRIPTION
**Pull request by nilotpalnandi**
## What changes were proposed in this pull request?
Currently,  "getserviceroles" subcommand of OM admin CLI displays only node ID along with its serviceRole. 
Example :
ozone admin om getserviceroles -id=ozone1
om2 : FOLLOWER
om3 : FOLLOWER
om1 : LEADER

Proposed changes is to include hostnames for each Node IDs.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-3246

## How was this patch tested?
Applied the patch and rebuilt ozone 
Created ozone docker cluster with OM HA using docker-compose
Ran "ozone  admin om getserviceroles" command

sample output :
ozone  admin om getserviceroles -id=id1
om1 : FOLLOWER (om1)
om3 : FOLLOWER (om3)
om2 : LEADER (om2)

### CODE REVIEW

**Comment by vivekratnavel** [comment]
@nilotpalnandi Thanks for working on this! Can you please resolve checkstyle issues and merge conflicts?

**Comment by bharatviswa504** [comment]
@nilotpalnandi 
Please rebase this on top of the latest master, this is targeted for 0.6.0 release, we can get this in once CI and rebase issues are addressed.

**Comment by vivekratnavel** [comment]
@elek Thanks for taking this up! I have been waiting for a long time for this feature. We might have to re-trigger builds to get a green on it-client test.

**Comment by vivekratnavel** [comment]
This is the failing test case:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 52.503 s <<< FAILURE! - in org.apache.hadoop.ozone.client.rpc.TestFailureHandlingByClientFlushDelay
[ERROR] testPipelineExclusionWithPipelineFailure(org.apache.hadoop.ozone.client.rpc.TestFailureHandlingByClientFlushDelay)  Time elapsed: 52.423 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.apache.hadoop.ozone.client.rpc.TestFailureHandlingByClientFlushDelay.testPipelineExclusionWithPipelineFailure(TestFailureHandlingByClientFlushDelay.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by elek** [comment]
c671d03dd7477d9b30913444fac663c9976b205d seems to be green for me.

**Comment by elek** [comment]
88347c5 is also green. I am merging it now. Thanks @nilotpalnandi the contribution.

**Pull request merged**
