### PR TITLE
HDDS-2363. Fail to create Ratis container.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-2363

### CODE REVIEW

**Comment by swagle** [comment]
Thanks @ChenSammi for the fix, changes look good to me. There seems to be a related integration test failure.

**Comment by ChenSammi** [comment]
Thanks @swagle for the review.  A new patch is submitted to address the issues.

**Comment by swagle** [comment]
+1 LGTM.

**Comment by mukul1987** [comment]
Thanks for working on this @ChenSammi, I cannot understand the changes, How does moving the createIfNeccessary function fixes the issue ?

**Comment by ChenSammi** [comment]
> 
> 
> Thanks for working on this @ChenSammi, I cannot understand the changes, How does moving the createIfNeccessary function fixes the issue ?

Hi @mukul1987 ,   because some of MetadataStoreBuilder caller want the createIfMissing to be true, and some want it to be false.  Current implementaion caches the first "org.rocksdb.Options" instance for each configuration. Every next time caller gets the same createIfMissing, it's self createIfMissing  input is ignored. 

For this "fail to crate Ratis container" case,  first time createIfMissing is "false", which will not create the directory for new containers, so the creation failed.

**Comment by anuengineer** [comment]
+1. LGTM. Thanks for the fix.

**Pull request merged**
