### PR TITLE
HDDS-2483. Fix Sonar warnings in HddsUtils

### PR DESCRIPTION
**Pull request by insideo**
## What changes were proposed in this pull request?

Add explicit return statements to each case branch to fix Sonar warnings.

## What is the link to the Apache JIRA

https://issues.apache.org/jira/browse/HDDS-2483

## How was this patch tested?

Ran local unit tests and rat, findbugs, checkstyle.

### CODE REVIEW

**Comment by insideo** [comment]
Unit test failures appear unrelated.

**Comment by dineshchitlangia** [comment]
Thank @adoroszlai for the review.

**Comment by anuengineer** [comment]
@insideo Awesome and welcome to patch world of Ozone. You have already contributed so much to the design, I am delighted to see this patch. Thank you very much.

**Comment by adoroszlai** [comment]
One minor request (to both @insideo and @dineshchitlangia): please pay attention to commit messages.  Including the Jira number makes it easier to track commits later.  (Fortunately we have a PR number in this case.)

**Comment by insideo** [comment]
> One minor request (to both @insideo and @dineshchitlangia): please pay attention to commit messages. Including the Jira number makes it easier to track commits later. (Fortunately we have a PR number in this case.)
Will do, sorry I missed that.

**Comment by dineshchitlangia** [comment]
@adoroszlai Thanks for catching that!

**Pull request merged**
