### PR TITLE
HDDS-3018. Fix TestContainerStateMachineFailures.java

### PR DESCRIPTION
**Pull request by bshashikant**
## What changes were proposed in this pull request?
The unit tests are written withe single node ratis into consideration. The expectation is the datanode fails, client should see an exception after next io as there is no new dn for new pipeline to form. Tuned watch, rpc and stale node timeouts.

## What is the link to the Apache JIRA
https://issues.apache.org/jira/browse/HDDS-3018

## How was this patch tested?

Ran the unit tests to verify the fix.

### CODE REVIEW

**Comment by adoroszlai** [comment]
```
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 494.349 s <<< FAILURE! - in org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineFailures
[ERROR] testValidateBCSIDOnDnRestart(org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineFailures)  Time elapsed: 134.042 s  <<< ERROR!
INTERNAL_ERROR org.apache.hadoop.ozone.om.exceptions.OMException: Allocated 0 blocks. Requested 1 blocks
```

https://github.com/adoroszlai/hadoop-ozone/runs/456410529
https://github.com/adoroszlai/hadoop-ozone/suites/469297412/artifacts/2033373

**Comment by adoroszlai** [comment]
@bshashikant it seems `testValidateBCSIDOnDnRestart` is still failing intermittently:

https://github.com/adoroszlai/hadoop-ozone/runs/460217262

**Comment by bshashikant** [comment]
> @bshashikant it seems `testValidateBCSIDOnDnRestart` is still failing intermittently:
> 
> https://github.com/adoroszlai/hadoop-ozone/runs/460217262

The test failure seems to be caused by sureFirePlugin crashed. Doesn't look related to the fix. @adoroszlai , can you please reverify?
 `
aused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /github/workspace/hadoop-ozone/integration-test && /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre/bin/java -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -javaagent:/home/user/.m2/repository/org/jacoco/org.jacoco.agent/0.8.3/org.jacoco.agent-0.8.3-runtime.jar=destfile=/github/workspace/hadoop-ozone/integration-test/target/jacoco.exec -jar /github/workspace/hadoop-ozone/integration-test/target/surefire/surefirebooter2072467495165129488.jar /github/workspace/hadoop-ozone/integration-test/target/surefire 2020-02-21T15-07-22_858-jvmRun1 surefire8996706673983742680tmp surefire_07780824442179183095tmp
[ERROR] Error occurred in starting fork, check output in log
`

**Comment by adoroszlai** [comment]
Sorry @bshashikant, I missed your comment.

There are 2 kinds of failures in the log:

1. The crash is due to calling `System.exit`.
```
[Datanode State Machine Thread - 0] ERROR statemachine.StateContext (StateContext.java:execute(420)) - Critical error occurred in StateMachine, setting shutDownMachine
[Datanode State Machine Thread - 0] ERROR statemachine.DatanodeStateMachine (DatanodeStateMachine.java:start(219)) - DatanodeStateMachine Shutdown due to an critical error
[Datanode State Machine Thread - 0] INFO  util.ExitUtil (ExitUtil.java:terminate(210)) - Exiting with status 1: ExitException
```

2. The test failure I mentioned.
```
[ERROR] testValidateBCSIDOnDnRestart(org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineFailures)  Time elapsed: 45.811 s  <<< FAILURE!
java.lang.AssertionError
...
  at org.junit.Assert.assertTrue(Assert.java:52)
  at org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineFailures.testValidateBCSIDOnDnRestart(TestContainerStateMachineFailures.java:624)
```

**Comment by adoroszlai** [comment]
It seems both kinds of failures still happen:

https://github.com/adoroszlai/hadoop-ozone/runs/472925889

**Comment by bshashikant** [comment]
> It seems both kinds of failures still happen:
> 
> https://github.com/adoroszlai/hadoop-ozone/runs/472925889

Thanks @adoroszlai for testing it out. If you have the logs for the failed scenarios , can you share one?

**Comment by adoroszlai** [comment]
> If you have the logs for the failed scenarios , can you share?

Sure, attached to the Jira issue.

**Comment by bshashikant** [comment]
@adoroszlai , can you plz rerun?

**Comment by adoroszlai** [comment]
@bshashikant I ran it a few days ago with latest commit and had failures, now repeated after merge from `master` and still have failures.  [Bundle for latest run attached](https://issues.apache.org/jira/secure/attachment/12996146/494640486.zip) to the Jira.

**Comment by bshashikant** [comment]
> @bshashikant I ran it a few days ago with latest commit and had failures, now repeated after merge from `master` and still have failures. [Bundle for latest run attached](https://issues.apache.org/jira/secure/attachment/12996146/494640486.zip) to the Jira.
> 
> https://github.com/adoroszlai/hadoop-ozone/runs/482610870
> https://github.com/adoroszlai/hadoop-ozone/runs/494640486
The issue seems to be happening because of multi raft change. Seems like its not able to create a pipeline for single node replication after a restart.
`2020-03-09 10:09:18,355 [main] INFO  ozone.MiniOzoneClusterImpl (MiniOzoneClusterImpl.java:lambda$waitForClusterToBeReady$0(172)) - Nodes are ready. Got 1 of 1 DN Heartbeats.
2020-03-09 10:09:18,355 [main] INFO  ozone.MiniOzoneClusterImpl (MiniOzoneClusterImpl.java:lambda$waitForClusterToBeReady$0(175)) - Cluster exits safe mode
2020-03-09 10:09:18,377 [EventQueue-PipelineReportForPipelineReportHandler] INFO  pipeline.PipelineStateManager (PipelineStateManager.java:openPipeline(131)) - Pipeline Pipeline[ Id: 688c4395-fb18-439c-8eae-d9071eb59e52, Nodes: 9096261b-515c-4f37-958b-ea61af077c73{ip: 172.17.0.2, host: b9fd1eda9192, networkLocation: /default-rack, certSerialId: null}, Type:RATIS, Factor:ONE, State:ALLOCATED, leaderId:9096261b-515c-4f37-958b-ea61af077c73, CreationTimestamp2020-03-09T10:09:17.426Z] moved to OPEN state
2020-03-09 10:09:18,376 [IPC Server handler 0 on 39803] WARN  block.BlockManagerImpl (BlockManagerImpl.java:allocateBlock(204)) - Pipeline creation failed for type:RATIS factor:ONE. Datanodes may be used up.
org.apache.hadoop.hdds.scm.exceptions.SCMException: Cannot create pipeline of factor 1 using 0 nodes. Used 1 nodes. Healthy nodes 1
	at org.apache.hadoop.hdds.scm.pipeline.RatisPipelineProvider.pickNodesNeverUsed(RatisPipelineProvider.java:100)
	at org.apache.hadoop.hdds.scm.pipeline.RatisPipelineProvider.create(RatisPipelineProvider.java:146)
	at org.apache.hadoop.hdds.scm.pipeline.PipelineFactory.create(PipelineFactory.java:63)
	at org.apache.hadoop.hdds.scm.pipeline.SCMPipelineManager.createPipeline(SCMPipelineManager.java:209)
	at org.apache.hadoop.hdds.scm.block.BlockManagerImpl.allocateBlock(BlockManagerImpl.java:199)
	at org.apache.hadoop.hdds.scm.server.SCMBlockProtocolServer.allocateBlock(SCMBlockProtocolServer.java:188)
	at org.apache.hadoop.hdds.scm.protocol.ScmBlockLocationProtocolServerSideTranslatorPB.allocateScmBlock(ScmBlockLocationProtocolServerSideTranslatorPB.java:159)
	at org.apache.hadoop.hdds.scm.protocol.ScmBlockLocationProtocolServerSideTranslatorPB.processMessage(ScmBlockLocationProtocolServerSideTranslatorPB.java:117)
	at org.apache.hadoop.hdds.server.OzoneProtocolMessageDispatcher.processRequest(OzoneProtocolMessageDispatcher.java:72)
	at org.apache.hadoop.hdds.scm.protocol.ScmBlockLocationProtocolServerSideTranslatorPB.send(ScmBlockLocationProtocolServerSideTranslatorPB.java:98)
	at org.apache.hadoop.hdds.protocol.proto.ScmBlockLocationProtocolProtos$ScmBlockLocationProtocolService$2.callBlockingMethod(ScmBlockLocationProtocolProtos.java:13157)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:876)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:822)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2682)
2020-03-09 10:09:18,386 [IPC Server handler 0 on 39803] ERROR block.BlockManagerImpl (BlockManagerImpl.java:allocateBlock(244)) - Unable to allocate a block for the size: 4194304, type: RATIS, factor: ONE
`
As a result of which allocateBlock call is failing.
cc @nandakumar131 @timmylicheng

**Comment by timmylicheng** [comment]
@bshashikant After multi-raft change, Ratis pipline (ONE or THREE) are created by BackgroundPipelineCreator and when auto creation is enabled, background thread will create Ratis One pipeline which will use up the datanode load limit for pipeline. If you wish to let allocateBlock to create pipeline instead of background thread, you can set ozone.scm.pipeline.creation.auto.factor.one to be false so that background thread will not create Ratis ONE pipeline automatically and release the load limit.

**Comment by bshashikant** [comment]
Thanks @timmylicheng . I think the problem seems to be arising out a race condition of sort. By the time, allocateBlock call comes to SCM, there is no pipeline of factor 1 . As a result of which allocateBlock call itself calls createPipeline and in the meantime, background thread creates the 1 node pipeline using up the dn, thereby failing allocateBlock call as the pipeline creation invoked as a part of allocateBlock failed, thereby failing the client write. What do you think?

**Comment by adoroszlai** [comment]
Thanks @bshashikant for the latest update.  It passed 20 runs: https://github.com/adoroszlai/hadoop-ozone/runs/519281188

However, it takes around 10 minutes to run this single test class.  `client` is already the longest running integration test suite.  I think we should either try to reduce the time required, or distribute the tests which take the most time by using class-level include/exclude filters (might prove to be difficult to maintain).

**Comment by elek** [comment]
/pending "I think we should either try to reduce the time required, or distribute the tests...."

**Comment by adoroszlai** [comment]
Thanks @bshashikant for the reducing the time required for this test to less than half.

We have 5 good runs so far (2 in PR, 3 in push), but also 3 runs with one or more timeouts waiting for cluster to be ready:

```
  at org.apache.hadoop.ozone.MiniOzoneClusterImpl.waitForClusterToBeReady(MiniOzoneClusterImpl.java:172)
  at org.apache.hadoop.ozone.client.rpc.TestContainerStateMachineFailures.init(TestContainerStateMachineFailures.java:147)
```

https://github.com/apache/hadoop-ozone/runs/794024040
https://github.com/apache/hadoop-ozone/runs/794041689
https://github.com/bshashikant/hadoop-ozone/runs/794022489

**Comment by adoroszlai** [comment]
5/20 runs failed with various errors:

```
2020-06-24T16:37:04.1145709Z [ERROR] Failures: 
2020-06-24T16:37:04.1213328Z [ERROR]   TestContainerStateMachineFailures.testContainerStateMachineFailures:219
```

```
2020-06-24T16:49:44.8410637Z [ERROR] Errors: 
2020-06-24T16:49:44.8414854Z [ERROR]   TestContainerStateMachineFailures.testApplyTransactionFailure:357 NullPointer
```

```
2020-06-24T17:03:02.2807334Z [ERROR] Errors: 
2020-06-24T17:03:02.2820978Z [ERROR]   TestContainerStateMachineFailures.testContainerStateMachineFailures:227 ? Timeout
2020-06-24T17:03:02.2821459Z [ERROR]   TestContainerStateMachineFailures.testUnhealthyContainer:304 ? Timeout Timed o...
2020-06-24T17:03:02.2821630Z [ERROR]   TestContainerStateMachineFailures.testValidateBCSIDOnDnRestart:614 ? Timeout T...
```

```
2020-06-24T17:04:50.3892566Z [ERROR] Failures: 
2020-06-24T17:04:50.3908120Z [ERROR]   TestContainerStateMachineFailures.testContainerStateMachineFailures:219
2020-06-24T17:04:50.3910934Z [ERROR] Errors: 
2020-06-24T17:04:50.3916393Z [ERROR]   TestContainerStateMachineFailures.testApplyTransactionFailure:357 NullPointer
```

```
2020-06-24T17:18:48.8448072Z [ERROR] Errors: 
2020-06-24T17:18:48.8448331Z [ERROR]   TestContainerStateMachineFailures.testContainerStateMachineFailures:227 ? Timeout
2020-06-24T17:18:48.8448591Z [ERROR]   TestContainerStateMachineFailures.testUnhealthyContainer:304 ? Timeout Timed o...
2020-06-24T17:18:48.8448865Z [ERROR]   TestContainerStateMachineFailures.testValidateBCSIDOnDnRestart:614 ? Timeout T...
```

Zip with logs: https://github.com/adoroszlai/hadoop-ozone/suites/836775093/artifacts/9406589

**Comment by adoroszlai** [comment]
Started 20 repetitions: https://github.com/adoroszlai/hadoop-ozone/runs/807906172

**Comment by adoroszlai** [comment]
/ready Time elapsed is around 60-100 seconds for 51e904a, much better than 10 minutes.

**Comment by adoroszlai** [comment]
Sorry, I just noticed that TestValidateBCSIDOnRestart needs to be repeated as well.  Triggered new run.

**Comment by bshashikant** [comment]
Thanks @adoroszlai for testing it out and for the review and merge.

**Pull request merged**
