### PR TITLE
HDDS-3806. Support recognize aws v2 Authorization header.

### PR DESCRIPTION
**Pull request by ChenSammi**
https://issues.apache.org/jira/browse/HDDS-3806

### CODE REVIEW

**Comment by elek** [comment]
Thanks to add this support @ChenSammi 

Can you please share some details about the testing? Do you have any recommendation for the client? Couldn't see any option in `aws cli` but ready to install any other (open source ;-)) tools to test it and merge.

**Comment by ChenSammi** [comment]
> 
> 
> Thanks to add this support @ChenSammi
> 
> Can you please share some details about the testing? Do you have any recommendation for the client? Couldn't see any option in `aws cli` but ready to install any other (open source ;-)) tools to test it and merge.

Marton,  aws sdk 1.10.* by default using V2 authrization header, and 1.11.* by default using V4 authrization header.  You can reproduce the issue with a 1.10.* aws client.

**Comment by ChenSammi** [comment]
Thanks @elek  for the review.

**Pull request merged**
